# -*- coding: utf-8 -*-
"""VectoRAG - Your Edu Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJfH_h1bzEtng6ypP-qL7ndEMRWex7ic

# ⚡ VectoRAG - Your EDU Assistant
### Google Colab + Streamlit


1.  **Install Dependencies:**  pytesseract, pdf2image, langchain-text-splitters, chromadb, and gdown,  tesseract-ocr and poppler-utils.

2. **Mount Google Drive & Configure Paths:** It mounts Google Drive to persist data and models. It then defines paths for storing extracted data, JSON files for text and visual elements, and the local PDF file. It also downloads the Cloud_Computing.pdf file if it's not already present.

3. **OCR + Visual Extraction:** This step performs Optical Character Recognition (OCR) on the PDF pages using pytesseract to extract text. It also uses opencv-python to identify and extract visual elements (tables, images) from the PDF pages. The extracted text is cleaned, and both text and visual elements are saved as JSON files in Google Drive for caching.

4. **Text Chunking:**  The extracted text from the PDF is then processed using LangChain's RecursiveCharacterTextSplitter. This breaks down the document into smaller, manageable chunks, which are more suitable for retrieval-augmented generation (RAG).

5. **ChromaDB Vector Storage:** The text chunks are then embedded into a vector database using ChromaDB. It uses the all-MiniLM-L6-v2 sentence transformer model to generate embeddings. If the collection is empty, it indexes all chunks; otherwise, it loads existing indexed chunks.

6. **LLM Initialization**: This step handles the loading of a pre-trained Large Language Model (LLM), specifically TinyLlama-1.1B-Chat-v1.0-GGUF. It attempts to install llama-cpp-python with GPU acceleration, falling back to CPU if GPU installation fails. The model is downloaded if not already present.

7. **Query Normalizer + Deduplicator:** This section defines utility functions for processing user queries. normalize_query cleans and corrects user input by mapping abbreviations and performing spell-checking against a domain-specific vocabulary. deduplicate_sentences removes redundant sentences from retrieved text.

8. **Web Fallback Engine:** This module provides functions (_wiki_summary, _wiki_full, _gfg) to fetch information from Wikipedia and GeeksforGeeks. This serves as a fallback mechanism if the document-based retrieval yields low confidence results, providing supplementary context for both chat and quiz generation.

9. **Retrieval Engine:** This core RAG component takes a user query, normalizes it, and queries the ChromaDB for relevant text chunks. It calculates a confidence score based on similarity. If confidence is low or no document context is found, it automatically fetches information from the web fallback engine.

10. **Template Quiz Generator:** This provides a deterministic quiz generation mechanism that doesn't rely on an LLM. It extracts terms and sentences from provided context and creates three types of questions: definition, fill-in-the-blank, and 'which is correct' questions.

11. **High-Speed Accurate MCQ Generator**:  This is the main quiz generation function. It first attempts to use the LLM to generate multiple-choice questions from the retrieved context. If the LLM is unavailable or fails to produce valid questions, it falls back to the template_quiz generator for robustness.

12. **Setup Cloudflared Tunnel:**  This prepares the cloudflared executable, which is used to create a secure tunnel to expose the Streamlit application running on the Colab environment to the internet.

13. **Install Streamlit:**  Installs the Streamlit library, which is used to build the interactive web application for the EDU Assistant.

14. **Write Streamlit App (app.py)**:  This cell writes the entire Streamlit application code into a file named app.py. This application integrates all the previous components: chat with document and quiz generation, leveraging the LLM and RAG functionalities.

15. **Launch Streamlit App:** Finally, this step clears any existing processes on port 8501, starts the Streamlit application, waits for it to load, and then initiates the Cloudflared tunnel, providing a publicly accessible URL to interact with the application.
"""

# ── STEP 1: INSTALL ALL DEPENDENCIES ────────────────────────────────────────
# Changes: added langchain-text-splitters, removed matplotlib-venn (unused)
!sudo apt-get install -y tesseract-ocr poppler-utils -q
!pip install -q \
    pytesseract pdf2image Pillow opencv-python numpy \
    requests beautifulsoup4 \
    langchain-text-splitters \
    sentence-transformers \
    chromadb \
    gdown 2>/dev/null

import os, re, cv2, numpy as np, pytesseract
from pdf2image import convert_from_path
from PIL import Image, ImageFilter
from google.colab import files, drive
print('✅ All dependencies installed.')

# ── STEP 2: MOUNT DRIVE & CONFIGURE PATHS ────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

import os, json
import gdown

# --- Config ---
GDRIVE_FILE_ID = '1walzCDlPmAN46mRdpZ9UREQXk7w3vhhw'
PDF_FILENAME   = 'Cloud_Computing.pdf'
DB_BASE_PATH   = '/content/drive/MyDrive/vector/extracted_data'
PDF_SUBDIR     = os.path.join(DB_BASE_PATH, 'Cloud_Computing')
os.makedirs(PDF_SUBDIR, exist_ok=True)

MARKER_PATH      = os.path.join(PDF_SUBDIR, '_processed.json')
TEXT_JSON_PATH   = os.path.join(PDF_SUBDIR, 'text_by_page.json')
VISUAL_JSON_PATH = os.path.join(PDF_SUBDIR, 'visual_elements_by_page.json')

# --- Download PDF if needed ---
if not os.path.exists(PDF_FILENAME):
    print(f'Downloading {PDF_FILENAME}...')
    gdown.download(id=GDRIVE_FILE_ID, output=PDF_FILENAME, quiet=False)
else:
    print(f'✅ {PDF_FILENAME} already present.')

# ── STEP 3: OCR + VISUAL EXTRACTION (with improved cleaning) ─────────────────


import cv2, numpy as np, pytesseract, json, os, re
from pdf2image import convert_from_path
from PIL import Image, ImageFilter

# --- OCR noise cleaner ---
_NOISE_LINE = re.compile(r'TECHNICAL PUBLICATIONS|an up-thrust|GTU\s*[:\.]', re.I)

def _clean_ocr(raw: str) -> str:
    lines = []
    for line in raw.splitlines():
        s = line.strip()
        if not s or len(s) < 4:
            continue
        if re.match(r'^\d+\s*[-]\s*\d+$', s):   # page numbers like "1 - 2"
            continue
        if _NOISE_LINE.search(s):                 # publisher footers
            continue
        alpha = sum(c.isalpha() or c.isspace() for c in s)
        if alpha / len(s) < 0.45:                 # mostly symbols/digits
            continue
        lines.append(s)
    return re.sub(r' {2,}', ' ', ' '.join(lines)).strip()

# --- Load cache or run extraction ---
extracted_text_by_page    = {}
extracted_visuals_by_page = {}

if os.path.exists(MARKER_PATH):
    try:
        with open(TEXT_JSON_PATH)   as f: extracted_text_by_page    = json.load(f)
        with open(VISUAL_JSON_PATH) as f: extracted_visuals_by_page = json.load(f)
        print(f'✅ Loaded cached data: {len(extracted_text_by_page)} pages.')
    except:
        pass

if not extracted_text_by_page:
    print('🚀 Running OCR + visual extraction (first time)...')
    pages = convert_from_path(PDF_FILENAME, dpi=300)

    for i, page_img in enumerate(pages):
        page_idx = i + 1

        # ── OCR: grayscale + sharpen + 3× effective zoom (300 DPI already high) ──
        gray = page_img.convert('L')
        sharp = gray.filter(ImageFilter.SHARPEN)
        raw_text = pytesseract.image_to_string(
            sharp,
            config='--psm 6 --oem 3 -c preserve_interword_spaces=1'
        )
        extracted_text_by_page[page_idx] = _clean_ocr(raw_text)

        # ── CV2 visual extraction (tables/diagrams) ──
        page_cv = cv2.cvtColor(np.array(page_img), cv2.COLOR_RGB2BGR)
        gray_cv = cv2.cvtColor(page_cv, cv2.COLOR_BGR2GRAY)
        thresh  = cv2.adaptiveThreshold(gray_cv, 255,
                    cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 11, 2)
        kernel  = cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))
        dilated = cv2.dilate(thresh, kernel, iterations=2)
        contours, _ = cv2.findContours(dilated, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        page_visuals = []
        total_area   = page_cv.shape[0] * page_cv.shape[1]
        for idx, cnt in enumerate(contours):
            x, y, w, h = cv2.boundingRect(cnt)
            area = w * h
            if total_area * 0.02 < area < total_area * 0.9:
                ar     = w / float(h)
                v_type = 'table' if (ar > 2.0 or ar < 0.5) else 'image'
                v_name = f'page_{page_idx}_{v_type}_{idx}.png'
                v_path = os.path.join(PDF_SUBDIR, v_name)
                cv2.imwrite(v_path, page_cv[y:y+h, x:x+w])
                page_visuals.append({'path': v_path, 'type': v_type})
        extracted_visuals_by_page[page_idx] = page_visuals

    # Save to Drive
    with open(TEXT_JSON_PATH,   'w') as f: json.dump(extracted_text_by_page,    f, indent=2)
    with open(VISUAL_JSON_PATH, 'w') as f: json.dump(extracted_visuals_by_page, f, indent=2)
    with open(MARKER_PATH,      'w') as f: json.dump({'processed': True},        f)
    print(f'✅ Done: {len(extracted_text_by_page)} pages processed.')

# ── STEP 4: TEXT CHUNKING (LangChain RecursiveCharacterTextSplitter) ─────────
# Changes: chunk_size 700→600, overlap 100→80, sorted keys fix retained
from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=600,
    chunk_overlap=80,
    separators=['\n\n', '\n', '.', ' ', '']
)

chunks = []
sorted_keys = sorted(extracted_text_by_page.keys(), key=lambda x: int(x))

for page_num in sorted_keys:
    split_docs = text_splitter.create_documents(
        [extracted_text_by_page[page_num]],
        metadatas=[{'page': int(page_num)}]
    )
    chunks.extend(split_docs)

print(f'✅ Chunking complete: {len(chunks)} chunks from {len(sorted_keys)} pages.')

# ── STEP 5: CHROMADB VECTOR STORAGE ─────────────────────────────────────────

import os, chromadb
from chromadb.utils import embedding_functions

DB_PATH = '/content/drive/MyDrive/vector/chromadb'
os.makedirs(DB_PATH, exist_ok=True)

client = chromadb.PersistentClient(path=DB_PATH)
emb_fn = embedding_functions.SentenceTransformerEmbeddingFunction(model_name='all-MiniLM-L6-v2')
collection = client.get_or_create_collection(name='vectorag_docs', embedding_function=emb_fn)

if collection.count() == 0:
    print(f'🚀 Indexing {len(chunks)} chunks into ChromaDB...')
    collection.add(
        ids       = [f'id_{i}' for i in range(len(chunks))],
        documents = [c.page_content for c in chunks],
        metadatas = [c.metadata for c in chunks]
    )
    print(f'✅ Indexed {collection.count()} chunks.')
else:
    print(f'✅ ChromaDB ready — {collection.count()} chunks loaded from Drive.')

# ── STEP 6: LLM INITIALIZATION (GPU-Accelerated TinyLlama) ──────────────────
# Changes: Q2_K model kept (fastest for Colab), safe import with fallback
import os, sys

MODEL_DIR  = '/content/drive/MyDrive/colab_models'
MODEL_PATH = os.path.join(MODEL_DIR, 'tinyllama-1.1b-chat-v1.0.Q2_K.gguf')
MODEL_URL  = 'https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q2_K.gguf'
os.makedirs(MODEL_DIR, exist_ok=True)

if not os.path.exists(MODEL_PATH):
    print('📥 Downloading TinyLlama Q2_K (fastest quantization)...')
    !wget -q -O {MODEL_PATH} {MODEL_URL}
    print('✅ Download complete!')

# Safe import — server won't crash if llama_cpp missing
try:
    from llama_cpp import Llama
    _LLAMA_AVAILABLE = True
except ImportError:
    _LLAMA_AVAILABLE = False
    print('⚠️ llama-cpp-python not installed. Attempting GPU install...')
    !FORCE_CMAKE=1 CMAKE_ARGS='-DLLAMA_CUBLAS=on' pip install -q llama-cpp-python --no-cache-dir 2>/dev/null
    try:
        from llama_cpp import Llama
        _LLAMA_AVAILABLE = True
    except ImportError:
        print('⚠️ GPU install failed. Trying CPU...')
        !pip install -q llama-cpp-python --no-cache-dir 2>/dev/null
        try:
            from llama_cpp import Llama
            _LLAMA_AVAILABLE = True
        except:
            _LLAMA_AVAILABLE = False
            print('❌ llama-cpp unavailable — will use template quiz mode')

llm = None
if _LLAMA_AVAILABLE and os.path.exists(MODEL_PATH):
    print('🚀 Loading TinyLlama onto GPU...')
    llm = Llama(model_path=MODEL_PATH, n_ctx=3072, n_gpu_layers=-1, n_threads=4, verbose=False)
    print('✅ TinyLlama ready.')

# ── STEP 7: QUERY NORMALIZER + DEDUPLICATOR ─────────────────────────────────
# Changes: expanded ABBREV_MAP, kept all original vocab
import re
from difflib import get_close_matches

DOMAIN_VOCAB = [
    'cloud computing','virtualization','infrastructure','saas','paas','iaas',
    'deployment','public cloud','private cloud','hybrid cloud','multicloud',
    'scalability','elasticity','load balancing','containerization','docker',
    'kubernetes','microservices','serverless','devops','pipeline',
    'database','nosql','sql','distributed','network','security','encryption',
    'authentication','authorization','firewall','vpn','api','rest','graphql',
    'machine learning','artificial intelligence','neural network','deep learning',
    'data mining','big data','hadoop','spark','kafka','storage','backup',
    'disaster recovery','sla','uptime','latency','throughput','bandwidth',
    'operating system','hypervisor','virtual machine','cluster','fault tolerance',
    'availability','reliability','monitoring','logging','governance','compliance',
]
ABBREV_MAP = {
    'cc':'cloud computing','vm':'virtual machine','vms':'virtual machines',
    'db':'database','os':'operating system','ai':'artificial intelligence',
    'ml':'machine learning','dl':'deep learning','k8s':'kubernetes',
    'sla':'service level agreement','dr':'disaster recovery','ha':'high availability',
    'api':'application programming interface','cdn':'content delivery network',
    'iaas':'infrastructure as a service','paas':'platform as a service',
    'saas':'software as a service','oop':'object oriented programming',
    'ds':'data structure','algo':'algorithm',
}
_VOCAB_TOKENS = {tok for phrase in DOMAIN_VOCAB for tok in phrase.split() if len(tok) > 3}

def normalize_query(raw: str) -> str:
    if not raw or not raw.strip(): return raw
    q = re.sub(r'[^a-z0-9\s]', ' ', raw.strip().lower())
    q = re.sub(r'\s+', ' ', q).strip()
    q = ' '.join(ABBREV_MAP.get(w, w) for w in q.split())
    corrected = []
    for w in q.split():
        if len(w) > 3 and w not in _VOCAB_TOKENS:
            m = get_close_matches(w, _VOCAB_TOKENS, n=1, cutoff=0.78)
            corrected.append(m[0] if m else w)
        else:
            corrected.append(w)
    return ' '.join(corrected)

def deduplicate_sentences(text: str) -> str:
    seen, unique = set(), []
    for s in re.split(r'(?<=[.!?])\s+', text.strip()):
        s = s.strip()
        if not s: continue
        key = re.sub(r'\s+', ' ', s.lower())
        if key not in seen:
            seen.add(key); unique.append(s)
    return ' '.join(unique)

print('✅ Query normalizer ready.')

# ── STEP 8: WEB FALLBACK ENGINE ──────────────────────────────────────────────
# Changes: added _wiki_full() for richer quiz context (full article not just summary)
import requests, urllib.parse
from bs4 import BeautifulSoup

def _wiki_summary(topic: str) -> str:
    try:
        enc  = urllib.parse.quote(topic.replace(' ', '_'))
        resp = requests.get(f'https://en.wikipedia.org/api/rest_v1/page/summary/{enc}',
                            timeout=8, headers={'User-Agent': 'VectorAG/3.0'})
        if resp.status_code == 200:
            e = resp.json().get('extract', '')
            if len(e) > 100: return e[:3000]
    except: pass
    return ''

def _wiki_full(topic: str) -> str:
    """Full Wikipedia article — gives more facts for quiz generation."""
    try:
        resp = requests.get('https://en.wikipedia.org/w/api.php',
            params={'action':'query','prop':'extracts','explaintext':True,
                    'titles':topic,'format':'json','exchars':6000},
            timeout=10, headers={'User-Agent': 'VectorAG/3.0'})
        if resp.status_code == 200:
            for p in resp.json().get('query',{}).get('pages',{}).values():
                txt = p.get('extract','')
                if len(txt) > 300: return txt[:5000]
    except: pass
    return ''

def _gfg(topic: str) -> str:
    try:
        r = requests.get(f'https://www.geeksforgeeks.org/?s={urllib.parse.quote(topic)}',
                         timeout=8, headers={'User-Agent': 'VectorAG/3.0'})
        soup = BeautifulSoup(r.text, 'html.parser')
        lt = soup.find('h2', class_='entry-title')
        if lt and lt.find('a'):
            ar = requests.get(lt.find('a')['href'], timeout=8, headers={'User-Agent': 'VectorAG/3.0'})
            t = ' '.join(p.get_text() for p in BeautifulSoup(ar.text,'html.parser').find_all('p')[:6])
            if len(t) > 200: return t[:2000]
    except: pass
    return ''

def fetch_web_context(topic: str) -> str:
    """For chat: summary is enough."""
    parts = []
    w = _wiki_summary(topic)
    if w: parts.append(f'[Wikipedia]\n{w}')
    if len(' '.join(parts)) < 500:
        g = _gfg(topic)
        if g: parts.append(f'[GeeksForGeeks]\n{g}')
    return '\n\n'.join(parts) if parts else ''

def fetch_web_quiz_context(topic: str) -> str:
    """For quiz: full article = more facts = better questions."""
    full = _wiki_full(topic)
    return full if full else fetch_web_context(topic)

print('✅ Web fallback engine ready.')

# ── STEP 9: RETRIEVAL ENGINE ─────────────────────────────────────────────────
# Changes: returns named dict, uses deduplicate_sentences, visual map lookup
import json

def retrieve_context(topic: str, collection, threshold=0.35) -> dict:
    cleaned = normalize_query(topic)
    if cleaned.lower() != topic.strip().lower():
        print(f'📝 Corrected: "{topic}" → "{cleaned}"')

    results = collection.query(
        query_texts=[cleaned], n_results=8,
        include=['documents', 'distances', 'metadatas']
    )
    docs  = results['documents'][0] if results['documents'] else []
    dists = results['distances'][0]  if results['distances']  else []
    metas = results['metadatas'][0]  if results['metadatas']  else []
    score = max(0.0, 1.0 - (dists[0] / 2.0)) if dists else 0.0

    if score >= threshold and docs:
        ctx = deduplicate_sentences('\n\n'.join(docs))
        pages = list({str(m.get('page','')) for m in metas})
        print(f'✅ Doc context retrieved (confidence: {score:.2f}) | Pages: {", ".join(sorted(pages))}')
        return {'cleaned_topic': cleaned, 'context': ctx,
                'source': 'doc', 'confidence': score, 'pages': pages}

    print(f'⚠️  Low doc confidence ({score:.2f}) — fetching from web...')
    web = fetch_web_context(cleaned)
    return {'cleaned_topic': cleaned, 'context': web,
            'source': 'web', 'confidence': score, 'pages': []}

def get_visual_assets(pages: list, visual_map: dict) -> list:
    """Return image/table paths for pages that had relevant context."""
    visuals = []
    for p in pages:
        for v in visual_map.get(str(p), []):
            if v['path'] not in [x['path'] for x in visuals]:
                visuals.append(v)
    return visuals

# Load visual map
try:
    with open(VISUAL_JSON_PATH) as f:
        visual_map = json.load(f)
    print(f'✅ Visual map loaded: {len(visual_map)} pages with assets.')
except:
    visual_map = {}
    print('⚠️  No visual map found.')

print('✅ Retrieval engine ready.')

# ── STEP 10: TEMPLATE QUIZ (no LLM needed, always works) ────────────────────
# Changes: 3 question types (definition, fill-blank, which-is-correct)
#          OCR noise filter on terms (_NOISE_TERMS)
#          Much better than original single-type fallback
import re, random

_NOISE_TERMS = {
    'gtu', 'marks', 'winter', 'summer', 'technical', 'publications',
    'fig', 'figure', 'table', 'note', 'page', 'unit', 'chapter',
}

def _get_defined_terms(text: str) -> list:
    """Strict term extractor — rejects OCR sentence fragments."""

    _SENTENCE_STARTERS = {
        'with','from','if','it','in','on','at','by','an','a','the','its','this',
        'that','these','those','when','where','which','who','what','how','since',
        'because','although','however','therefore','thus','hence','while','both',
        'each','some','most','all','any','for','as','but','so','yet','nor','or',
    }
    _GENERIC = {
        'internet connection','power consumption','data storage','market adaptability',
        'group collaboration','document access','software updates','computer costs',
    }
    raw = re.findall(r'([A-Z][a-zA-Z-]{2,20}(?:\s+[a-zA-Z-]{2,20}){0,3})\s*[:\-]\s*([^.\n]{20,150})', text)
    seen, result = set(), []
    for term, defn in raw:
        term, defn = term.strip(), defn.strip()
        tl, words = term.lower(), term.split()
        if not 1 <= len(words) <= 4: continue
        if words[0].lower() in _SENTENCE_STARTERS: continue
        if any(n in tl for n in _NOISE_TERMS): continue
        if tl in _GENERIC: continue
        if sum(c.isalpha() or c.isspace() for c in term) / len(term) < 0.92: continue
        if any(len(w) < 2 for w in words): continue
        if words[-1].lower() in {'the','a','an','of','in','on','at','to','and','or'}: continue
        if sum(c.isalpha() or c.isspace() for c in defn) / len(defn) < 0.60: continue
        if len(re.findall(r'[0-9/|¢£]', defn)) > 4: continue
        if len(defn.split()) < 4: continue
        if defn[0].islower() and defn.split()[0] not in {'a','an','the','it','its','this','that'}: continue
        if term.isupper() and len(term) > 5: continue
        if tl not in seen:
            seen.add(tl); result.append((term, defn[:120]))
    return result

def generate_template_quiz(context: str, topic: str, num_q: int) -> list:
    random.seed(42)
    sents = [s.strip() for s in re.split(r'(?<=[.!?])\s+', context)
             if 50 < len(s.strip()) < 300]
    terms = _get_defined_terms(context)
    questions = []

    # Type 1: Definition questions (highest quality)
    if len(terms) >= 4:
        defns = [d for _, d in terms]
        for term, defn in terms:
            if len(questions) >= num_q: break
            others = [d for d in defns if d != defn]
            random.shuffle(others)
            if len(others) < 3: continue
            opts = [defn] + others[:3]; random.shuffle(opts)
            questions.append({'question': f"What is '{term}'?",
                              'options': opts, 'answer': defn,
                              'explanation': f'{term}: {defn}'})

    # Type 2: Fill-in-the-blank
    for sent in sents:
        if len(questions) >= num_q: break
        words = sent.split()
        cands = [w.rstrip('.,;:') for w in words[2:] if len(w.rstrip('.,;:')) > 5 and w[0].isupper()]
        if not cands: cands = [w.rstrip('.,;:') for w in words[3:] if len(w.rstrip('.,;:')) > 6]
        if not cands: continue
        blank = cands[0]
        blanked = sent.replace(blank, '______', 1)
        if '______' not in blanked: continue
        pool = list({w for w in re.findall(r'\b[A-Za-z]{5,}\b', context) if w.lower() != blank.lower()})
        random.shuffle(pool)
        if len(pool) < 3: continue
        opts = [blank] + pool[:3]; random.shuffle(opts)
        questions.append({'question': f"Fill in the blank: '{blanked[:180]}'",
                          'options': opts, 'answer': blank,
                          'explanation': f"Complete sentence: '{sent[:200]}'"})

    # Type 3: Which statement is correct
    for sent in sents:
        if len(questions) >= num_q: break
        if any(sent[:50] in q.get('explanation','') for q in questions): continue
        others = [s[:140] for s in sents if s != sent and len(s) > 50]
        random.shuffle(others)
        if len(others) < 3: continue
        opts = [sent[:140]] + others[:3]; random.shuffle(opts)
        questions.append({'question': f"Which statement about '{topic}' is correct?",
                          'options': opts, 'answer': sent[:140],
                          'explanation': f"From document: '{sent[:200]}'"})

    return questions[:num_q]

print('✅ Template quiz generator ready.')

# ── STEP 11: HIGH-SPEED ACCURATE MCQ GENERATOR (LLM + Template fallback) ────
# Changes:
#   • Web quiz uses _wiki_full() for more content → more question variety
#   • Template fallback is now smart (3 question types) not dumb repeated questions
#   • LLM prompt tightened for faster token generation
import re, json

def _safe_json_parse(raw: str) -> list:
    for pat in [r'\[\s*\{.*?\}\s*\]', r'\[.*?\]']:
        m = re.search(pat, raw, re.DOTALL)
        if m:
            try: return json.loads(m.group(0))
            except:
                try: return json.loads(re.sub(r',\s*([}\]])', r'\1', m.group(0)))
                except: continue
    return []

def _validate_questions(raw_list: list) -> list:
    valid = []
    for q in raw_list:
        if not isinstance(q, dict): continue
        if not (isinstance(q.get('question'), str) and len(q['question']) > 10): continue
        if not (isinstance(q.get('options'), list) and len(q['options']) == 4): continue
        if not all(isinstance(o, str) and len(o) > 1 for o in q['options']): continue
        if not (isinstance(q.get('answer'), str) and q['answer'] in q['options']): continue
        q.setdefault('explanation', f"Correct answer: {q['answer']}")
        valid.append(q)
    return valid

def generate_mcq_quiz(raw_topic: str, collection, num_questions: int = 5) -> dict:
    """
    Full pipeline:
    1. Normalize + correct query
    2. Retrieve from ChromaDB (deduplicated)
    3. Auto web fallback with full Wikipedia article
    4. LLM generation if available, else smart template quiz
    5. JSON parsing + validation
    """
    result     = retrieve_context(raw_topic, collection)
    topic      = result['cleaned_topic']
    context    = result['context']
    source     = result['source']
    confidence = result['confidence']

    # Enrich with web when doc confidence is low
    if source in ('web', 'doc_low') or not context.strip():
        web = fetch_web_quiz_context(topic)
        if web:
            context = web if not context.strip() else context + '\n\n' + web
            if not context.strip(): source = 'web'

    if not context.strip():
        print(f'❌ No context found for "{topic}"')
        return {'questions': [], 'source': source, 'confidence': confidence}

    questions = []

    if llm:
        prompt = (
            f'[INST] <<SYS>>\n'
            f'Generate exactly {num_questions} MCQ questions from the context.\n'
            f'Rules: 4 options each, "answer" = exact correct option, add "explanation", no duplicates, JSON only.\n'
            f'<</SYS>>\n\n'
            f'Context:\n{context[:2800]}\n\n'
            f'[{{"question":"...","options":["A","B","C","D"],"answer":"A","explanation":"..."}}]\n'
            f'Generate {num_questions}: [/INST]'
        )
        out       = llm.create_chat_completion(
            messages=[{'role': 'user', 'content': prompt}],
            max_tokens=3500, temperature=0.05, repeat_penalty=1.15
        )
        questions = _validate_questions(_safe_json_parse(out['choices'][0]['message']['content']))
        print(f'✅ LLM: {len(questions)}/{num_questions} valid questions')

    if not questions:
        questions = generate_template_quiz(context, topic, num_questions)
        print(f'✅ Template: {len(questions)}/{num_questions} questions | source: {source.upper()}')

    return {
        'topic':      topic,
        'questions':  questions[:num_questions],
        'source':     source,
        'confidence': confidence,
    }

print('✅ MCQ generator ready.')

# ── STEP 12: SETUP CLOUDFLARED TUNNEL ────────────────────────────────────────
print('Downloading cloudflared...')
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64
!mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
!cloudflared --version
print('✅ cloudflared ready.')

# ── STEP 13: INSTALL STREAMLIT ───────────────────────────────────────────────
!pip install -q streamlit
print('✅ Streamlit installed.')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import os, json, re, requests, urllib.parse
# import chromadb
# from llama_cpp import Llama
# from sentence_transformers import SentenceTransformer
# from chromadb.utils import embedding_functions
# from bs4 import BeautifulSoup
# from difflib import get_close_matches
# from PIL import ImageFilter
# import random
# 
# # ── PAGE CONFIG ───────────────────────────────────────────────────────────────
# st.set_page_config(layout='wide', page_title='VectoRAG — Your EDU Assistant ', page_icon='⚡')
# 
# # ── PATHS ─────────────────────────────────────────────────────────────────────
# MODEL_PATH      = '/content/drive/MyDrive/colab_models/tinyllama-1.1b-chat-v1.0.Q2_K.gguf'
# DB_PATH         = '/content/drive/MyDrive/vector/chromadb'
# VISUAL_MAP_PATH = '/content/drive/MyDrive/vector/extracted_data/Cloud_Computing/visual_elements_by_page.json'
# 
# # ── DOMAIN VOCAB ──────────────────────────────────────────────────────────────
# _ABBREV = {
#     'cc':'cloud computing','vm':'virtual machine','db':'database','os':'operating system',
#     'ai':'artificial intelligence','ml':'machine learning','dl':'deep learning',
#     'k8s':'kubernetes','api':'application programming interface',
#     'iaas':'infrastructure as a service','paas':'platform as a service',
#     'saas':'software as a service','oop':'object oriented programming',
#     'ds':'data structure','algo':'algorithm','ha':'high availability',
#     'sla':'service level agreement','dr':'disaster recovery',
# }
# _VOCAB = [
#     'cloud computing','virtualization','infrastructure','saas','paas','iaas',
#     'deployment','scalability','elasticity','load balancing','containerization',
#     'docker','kubernetes','microservices','serverless','devops','database',
#     'nosql','sql','distributed','network','security','encryption',
#     'machine learning','artificial intelligence','neural network','deep learning',
#     'operating system','virtual machine','fault tolerance','algorithm','data structure',
# ]
# _VOCAB_TOKENS = {t for p in _VOCAB for t in p.split() if len(t) > 3}
# _NOISE_TERMS  = {'gtu','marks','winter','summer','technical','publications',
#                  'fig','figure','table','note','page','unit','chapter'}
# 
# # ── HELPERS ───────────────────────────────────────────────────────────────────
# def normalize_query(raw):
#     if not raw or not raw.strip(): return raw
#     q = re.sub(r'[^a-z0-9\s]', ' ', raw.strip().lower())
#     q = re.sub(r'\s+', ' ', q).strip()
#     q = ' '.join(_ABBREV.get(w, w) for w in q.split())
#     corrected = []
#     for w in q.split():
#         if len(w) > 3 and w not in _VOCAB_TOKENS:
#             from difflib import get_close_matches
#             m = get_close_matches(w, _VOCAB_TOKENS, n=1, cutoff=0.78)
#             corrected.append(m[0] if m else w)
#         else:
#             corrected.append(w)
#     return ' '.join(corrected)
# 
# def dedup_sents(text):
#     seen, out = set(), []
#     for s in re.split(r'(?<=[.!?])\s+', text.strip()):
#         s = s.strip()
#         key = re.sub(r'\s+', ' ', s.lower())
#         if s and key not in seen:
#             seen.add(key); out.append(s)
#     return ' '.join(out)
# 
# def _wiki_summary(topic):
#     try:
#         r = requests.get(
#             f'https://en.wikipedia.org/api/rest_v1/page/summary/{urllib.parse.quote(topic.replace(" ","_"))}',
#             timeout=8, headers={'User-Agent':'VectorAG/3.0'})
#         if r.status_code == 200:
#             e = r.json().get('extract','')
#             if len(e) > 100: return e[:3000]
#     except: pass
#     return ''
# 
# def _wiki_full(topic):
#     try:
#         r = requests.get('https://en.wikipedia.org/w/api.php',
#             params={'action':'query','prop':'extracts','explaintext':True,
#                     'titles':topic,'format':'json','exchars':6000},
#             timeout=10, headers={'User-Agent':'VectorAG/3.0'})
#         if r.status_code == 200:
#             for p in r.json().get('query',{}).get('pages',{}).values():
#                 t = p.get('extract','')
#                 if len(t) > 300: return t[:5000]
#     except: pass
#     return ''
# 
# def _gfg(topic):
#     try:
#         r = requests.get(f'https://www.geeksforgeeks.org/?s={urllib.parse.quote(topic)}',
#                          timeout=8, headers={'User-Agent':'VectorAG/3.0'})
#         soup = BeautifulSoup(r.text,'html.parser')
#         lt = soup.find('h2', class_='entry-title')
#         if lt and lt.find('a'):
#             ar = requests.get(lt.find('a')['href'], timeout=8, headers={'User-Agent':'VectorAG/3.0'})
#             t = ' '.join(p.get_text() for p in BeautifulSoup(ar.text,'html.parser').find_all('p')[:6])
#             if len(t) > 200: return t[:2000]
#     except: pass
#     return ''
# 
# def fetch_web(topic):
#     parts = []
#     w = _wiki_summary(topic)
#     if w: parts.append(f'[Wikipedia]\n{w}')
#     if len(' '.join(parts)) < 500:
#         g = _gfg(topic)
#         if g: parts.append(f'[GeeksForGeeks]\n{g}')
#     return '\n\n'.join(parts) if parts else ''
# 
# def get_context(topic, collection, threshold=0.35):
#     cleaned = normalize_query(topic)
#     results = collection.query(query_texts=[cleaned], n_results=8,
#                                include=['documents','distances','metadatas'])
#     docs  = results['documents'][0] if results['documents'] else []
#     dists = results['distances'][0]  if results['distances']  else []
#     metas = results['metadatas'][0]  if results['metadatas']  else []
#     score = max(0.0, 1.0-(dists[0]/2.0)) if dists else 0.0
#     pages = [str(m.get('page','')) for m in metas]
#     if score >= threshold and docs:
#         return cleaned, dedup_sents('\n\n'.join(docs)), 'doc', score, pages
#     return cleaned, fetch_web(cleaned), 'web', score, []
# 
# def _get_terms(text):
#     """Strict term extractor — rejects OCR sentence fragments."""
# 
#     _SENTENCE_STARTERS = {
#         'with','from','if','it','in','on','at','by','an','a','the','its','this',
#         'that','these','those','when','where','which','who','what','how','since',
#         'because','although','however','therefore','thus','hence','while','both',
#         'each','some','most','all','any','for','as','but','so','yet','nor','or',
#     }
#     _GENERIC = {
#         'internet connection','power consumption','data storage','market adaptability',
#         'group collaboration','document access','software updates','computer costs',
#     }
#     raw = re.findall(r'([A-Z][a-zA-Z-]{2,20}(?:\s+[a-zA-Z-]{2,20}){0,3})\s*[:\-]\s*([^.\n]{20,150})', text)
#     seen, result = set(), []
#     for term, defn in raw:
#         term, defn = term.strip(), defn.strip()
#         tl, words = term.lower(), term.split()
#         if not 1 <= len(words) <= 4: continue
#         if words[0].lower() in _SENTENCE_STARTERS: continue
#         if any(n in tl for n in _NOISE_TERMS): continue
#         if tl in _GENERIC: continue
#         if sum(c.isalpha() or c.isspace() for c in term) / len(term) < 0.92: continue
#         if any(len(w) < 2 for w in words): continue
#         if words[-1].lower() in {'the','a','an','of','in','on','at','to','and','or'}: continue
#         if sum(c.isalpha() or c.isspace() for c in defn) / len(defn) < 0.60: continue
#         if len(re.findall(r'[0-9/|¢£]', defn)) > 4: continue
#         if len(defn.split()) < 4: continue
#         if defn[0].islower() and defn.split()[0] not in {'a','an','the','it','its','this','that'}: continue
#         if term.isupper() and len(term) > 5: continue
#         if tl not in seen:
#             seen.add(tl); result.append((term, defn[:120]))
#     return result
# 
# def template_quiz(context, topic, num_q):
#     random.seed(42)
#     sents = [s.strip() for s in re.split(r'(?<=[.!?])\s+', context) if 50 < len(s.strip()) < 300]
#     terms = _get_terms(context)
#     questions = []
#     if len(terms) >= 4:
#         defns = [d for _,d in terms]
#         for term, defn in terms:
#             if len(questions) >= num_q: break
#             others = [d for d in defns if d != defn]
#             random.shuffle(others)
#             if len(others) < 3: continue
#             opts = [defn]+others[:3]; random.shuffle(opts)
#             questions.append({'question':f"What is '{term}'?",'options':opts,
#                               'answer':defn,'explanation':f'{term}: {defn}'})
#     for sent in sents:
#         if len(questions) >= num_q: break
#         words = sent.split()
#         cands = [w.rstrip('.,;:') for w in words[2:] if len(w.rstrip('.,;:'))>5 and w[0].isupper()]
#         if not cands: cands=[w.rstrip('.,;:') for w in words[3:] if len(w.rstrip('.,;:'))>6]
#         if not cands: continue
#         blank=cands[0]; blanked=sent.replace(blank,'______',1)
#         if '______' not in blanked: continue
#         pool=list({w for w in re.findall(r'\b[A-Za-z]{5,}\b',context) if w.lower()!=blank.lower()})
#         random.shuffle(pool)
#         if len(pool)<3: continue
#         opts=[blank]+pool[:3]; random.shuffle(opts)
#         questions.append({'question':f"Fill in the blank: '{blanked[:180]}'",'options':opts,
#                           'answer':blank,'explanation':f"Complete sentence: '{sent[:200]}'"})
#     for sent in sents:
#         if len(questions) >= num_q: break
#         if any(sent[:50] in q.get('explanation','') for q in questions): continue
#         others=[s[:140] for s in sents if s!=sent and len(s)>50]
#         random.shuffle(others)
#         if len(others)<3: continue
#         opts=[sent[:140]]+others[:3]; random.shuffle(opts)
#         questions.append({'question':f"Which statement about '{topic}' is correct?",
#                           'options':opts,'answer':sent[:140],
#                           'explanation':f"From document: '{sent[:200]}'"})
#     return questions[:num_q]
# 
# def safe_json_parse(raw):
#     for pat in [r'\[\s*\{.*?\}\s*\]', r'\[.*?\]']:
#         m = re.search(pat, raw, re.DOTALL)
#         if m:
#             try: return json.loads(m.group(0))
#             except:
#                 try: return json.loads(re.sub(r',\s*([}\]])', r'\1', m.group(0)))
#                 except: continue
#     return []
# 
# def validate_q(raw):
#     valid = []
#     for q in raw:
#         if not isinstance(q,dict): continue
#         if not (isinstance(q.get('question'),str) and len(q['question'])>10): continue
#         if not (isinstance(q.get('options'),list) and len(q['options'])==4): continue
#         if not all(isinstance(o,str) and len(o)>1 for o in q['options']): continue
#         if not (isinstance(q.get('answer'),str) and q['answer'] in q['options']): continue
#         q.setdefault('explanation',f"Correct: {q['answer']}")
#         valid.append(q)
#     return valid
# 
# def extractive_answer(question, context, n=4):
#     q_words = set(re.findall(r'\b[a-z]{3,}\b', question.lower()))
#     sents = [s.strip() for s in re.split(r'(?<=[.!?])\s+', context) if len(s.strip())>30]
#     scored = sorted(sents, key=lambda s: len(q_words & set(re.findall(r'\b[a-z]{3,}\b',s.lower()))), reverse=True)
#     top = [s for s in scored[:n] if any(w in s.lower() for w in q_words)]
#     order = {s:i for i,s in enumerate(sents)}
#     top.sort(key=lambda s: order.get(s,999))
#     return ' '.join(top) if top else ' '.join(sents[:3])
# 
# # ── RESOURCE LOADING ──────────────────────────────────────────────────────────
# @st.cache_resource
# def load_resources():
#     try:
#         from llama_cpp import Llama
#         llm = Llama(model_path=MODEL_PATH, n_ctx=3072, n_gpu_layers=-1, n_threads=4, verbose=False)
#     except Exception as e:
#         st.warning(f'LLM unavailable: {e} — template quiz mode active')
#         llm = None
#     client = chromadb.PersistentClient(path=DB_PATH)
#     emb    = embedding_functions.SentenceTransformerEmbeddingFunction(model_name='all-MiniLM-L6-v2')
#     col    = client.get_or_create_collection(name='vectorag_docs', embedding_function=emb)
#     try:
#         with open(VISUAL_MAP_PATH) as f: vmap = json.load(f)
#     except: vmap = {}
#     return llm, col, vmap
# 
# llm, collection, visual_map = load_resources()
# 
# # ── SESSION STATE ─────────────────────────────────────────────────────────────
# for key, default in [('messages',[]),('quiz_data',[]),('user_answers',{}),
#                      ('quiz_source',''),('quiz_confidence',0.0),('quiz_topic','')]:
#     if key not in st.session_state: st.session_state[key] = default
# 
# # ── UI ────────────────────────────────────────────────────────────────────────
# st.title('⚡ VectorAG — Your Edu Assistant')
# tab1, tab2 = st.tabs(['💬 Chat with Document', '📝 Quiz Generator'])
# 
# # ── TAB 1: CHAT ───────────────────────────────────────────────────────────────
# with tab1:
#     for msg in st.session_state.messages:
#         with st.chat_message(msg['role']):
#             st.markdown(msg['content'])
#             for v in msg.get('visuals',[]):
#                 if isinstance(v,dict) and 'path' in v and os.path.exists(v['path']):
#                     st.image(v['path'], caption=v.get('type','').title())
# 
#     if prompt := st.chat_input('Ask anything about the document (Cloud Computing)...'):
#         st.session_state.messages.append({'role':'user','content':prompt})
#         with st.chat_message('user'): st.markdown(prompt)
#         with st.chat_message('assistant'):
#             with st.spinner('Thinking...'):
#                 cleaned, context, source, conf, pages = get_context(prompt, collection)
#                 visuals = []
#                 for p in set(pages):
#                     for v in visual_map.get(str(p),[]):
#                         if os.path.exists(v.get('path','')):
#                             visuals.append(v)
# 
#                 if llm and context.strip():
#                     full_prompt = (
#                         '[INST] <<SYS>>\nYou are a concise academic assistant. '
#                         'Answer using ONLY the context. Max 4 sentences. No preamble.\n<</SYS>>\n\n'
#                         f'Context:\n{context[:2000]}\n\nQuestion: {prompt}\nAnswer: [/INST]'
#                     )
#                     out    = llm.create_chat_completion(messages=[{'role':'user','content':full_prompt}],
#                                                         max_tokens=300, temperature=0.1, repeat_penalty=1.3)
#                     answer = re.sub(r'^(Based on[^.]*\.\s*|The context[^.]*\.\s*)','',
#                                     out['choices'][0]['message']['content'].strip(), flags=re.I)
#                 elif context.strip():
#                     answer = extractive_answer(prompt, context)
#                 else:
#                     answer = 'No relevant information found.'
# 
#                 badge  = '📄 Doc' if source == 'doc' else '🌐 Web'
#                 answer += f'\n\n*Source: {badge} | Confidence: {conf:.0%}*'
#                 st.markdown(answer)
#                 for v in visuals:
#                     st.image(v['path'], caption=v.get('type','').title())
#                 st.session_state.messages.append({'role':'assistant','content':answer,'visuals':visuals})
# 
# # ── TAB 2: QUIZ ───────────────────────────────────────────────────────────────
# with tab2:
#     st.header('📝 Quiz Generator')
# 
# 
#     quiz_topic = st.text_input('Quiz Topic', placeholder='e.g. cloud deployment, vm, k8s, IaaS')
#     num_q      = st.slider('Number of Questions', 1, 20, 5)
# 
#     if st.button('🚀 Generate Quiz'):
#         if quiz_topic.strip():
#             with st.spinner('Generating quiz...'):
#                 st.session_state.user_answers = {}
#                 st.session_state.quiz_data    = []
# 
#                 cleaned, context, source, conf, pages = get_context(quiz_topic, collection)
# 
#                 if cleaned.lower() != quiz_topic.strip().lower():
#                     st.info(f'📝 Interpreted as: **"{cleaned}"**')
# 
#                 # Enrich with full Wikipedia when doc confidence low
#                 if source == 'web' or not context.strip():
#                     full = _wiki_full(cleaned)
#                     if full:
#                         context = full if not context.strip() else context + '\n\n' + full
# 
#                 if source == 'web':
#                     st.warning('📡 Not in document — using Wikipedia')
#                 else:
#                     st.success(f'📄 From document — confidence: {conf:.0%}')
# 
#                 if not context.strip():
#                     st.error('❌ No content found. Try another topic or check your connection.')
#                     st.stop()
# 
#                 st.session_state.quiz_source     = source
#                 st.session_state.quiz_confidence = conf
#                 st.session_state.quiz_topic      = cleaned
# 
#                 questions = []
#                 if llm:
#                     prompt = (
#                         f'[INST] <<SYS>>\nGenerate exactly {num_q} MCQ questions.\n'
#                         'Rules: 4 options each, "answer"=exact correct option text, add "explanation", no duplicates, JSON only.\n'
#                         f'<</SYS>>\n\nContext:\n{context[:2800]}\n\n'
#                         '[{"question":"...","options":["A","B","C","D"],"answer":"A","explanation":"..."}]\n'
#                         f'Generate {num_q}: [/INST]'
#                     )
#                     out       = llm.create_chat_completion(
#                         messages=[{'role':'user','content':prompt}],
#                         max_tokens=3500, temperature=0.05, repeat_penalty=1.15)
#                     questions = validate_q(safe_json_parse(out['choices'][0]['message']['content']))
# 
#                 if not questions:
#                     questions = template_quiz(context, cleaned, num_q)
# 
#                 st.session_state.quiz_data = questions
#                 if not questions:
#                     st.error('⚠️ Could not generate questions. Try a different topic.')
#         else:
#             st.warning('Please enter a topic.')
# 
#     # ── Display questions ─────────────────────────────────────────────────────
#     if st.session_state.quiz_data:
#         total = len(st.session_state.quiz_data)
#         badge = '📄 Doc' if st.session_state.quiz_source=='doc' else '🌐 Web'
#         st.markdown(f'---\n**{total} questions** | Source: {badge}')
# 
#         for i, q in enumerate(st.session_state.quiz_data):
#             st.subheader(f'Question {i+1} / {total}')
#             st.write(q['question'])
#             choice = st.radio('', q['options'], key=f'q_{i}', label_visibility='collapsed')
#             st.session_state.user_answers[i] = choice
#             st.markdown('---')
# 
#         if st.button('🏁 Submit & See Results'):
#             correct = sum(1 for i,q in enumerate(st.session_state.quiz_data)
#                          if st.session_state.user_answers.get(i)==q['answer'])
#             pct   = (correct/total)*100
#             grade = 'A' if pct>=90 else 'B' if pct>=75 else 'C' if pct>=60 else 'D' if pct>=50 else 'F'
# 
#             st.header('📊 Results')
#             c1,c2,c3 = st.columns(3)
#             c1.metric('Correct', f'{correct}/{total}')
#             c2.metric('Score',   f'{pct:.1f}%')
#             c3.metric('Grade',   grade)
#             st.markdown('---')
# 
#             for i,q in enumerate(st.session_state.quiz_data):
#                 ua = st.session_state.user_answers.get(i)
#                 if ua == q['answer']:
#                     st.success(f'✅ Q{i+1}: Correct!')
#                 else:
#                     st.error(f'❌ Q{i+1}: Wrong')
#                     st.write(f'Correct: **{q["answer"]}**')
#                 with st.expander(f'💡 Explanation — Q{i+1}'):
#                     st.write(q.get('explanation',''))
# 
#             if pct==100: st.balloons()
#             elif pct>=60: st.success('Good job! Keep going.')
#             else: st.error('Keep studying — you can improve!')
# 
#             st.session_state.quiz_data    = []
#             st.session_state.user_answers = {}
#

# ── STEP 14: LAUNCH ──────────────────────────────────────────────────────────
import subprocess, time

!fuser -k 8501/tcp
print('✅ Port cleared.')

with open('streamlit_logs.txt', 'w') as f:
    subprocess.Popen(['streamlit', 'run', 'app.py', '--server.port', '8501'],
                     stdout=f, stderr=f)

print('⏳ Waiting 25s for models to load...')
for i in range(25, 0, -1):
    print(f'  {i}s...', end='\r')
    time.sleep(1)

print('\n✅ Ready! Opening tunnel...')
!cloudflared tunnel --url http://127.0.0.1:8501