# -*- coding: utf-8 -*-
"""VectoRAG - Teachers .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FUj2xB0mhREwO2iS9LlnUL-Jl_JQjchh
"""

!sudo apt-get install -y tesseract-ocr
!pip install pytesseract pdf2image Pillow
# Install Poppler for PDF processing
!apt-get install -y poppler-utils

import pytesseract
from pdf2image import convert_from_path
from PIL import Image
import os
from google.colab import files

import cv2
import numpy as np
import pytesseract
import re
import os

# --- Step 1: Specify your scanned PDF file path --
# Install gdown if not already installed
!pip install -q gdown
import gdown

gdrive_file_id = '1walzCDlPmAN46mRdpZ9UREQXk7w3vhhw'
pdf_filename = 'Cloud Computing.pdf' # Desired local filename

print(f"Downloading PDF from Google Drive (ID: {gdrive_file_id}) as {pdf_filename}...")
try:
    gdown.download(id=gdrive_file_id, output=pdf_filename, quiet=False)
    print(f"Successfully downloaded {pdf_filename}.")
except Exception as e:
    print(f"Error downloading PDF from Google Drive: {e}")
    print("Please ensure the file ID is correct and the file has appropriate sharing permissions (e.g., 'Anyone with the link' can view).")
    pdf_filename = None # Indicate that download failed


if pdf_filename and os.path.exists(pdf_filename):
    print(f"Using PDF from Colab files: {pdf_filename}")
else:
    print("PDF file not available for processing. Please check the download step.")
    # Exit or handle error gracefully if PDF is crucial for subsequent steps


# Create a directory to save extracted diagrams and text
output_dir = "extracted_content"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
    print(f"Created directory: {output_dir}")

# --- PDF Processing: Convert PDF to images ---
print("Converting PDF to images...")
try:
    # You might need to adjust the dpi based on your scanned document's quality
    pages = convert_from_path(pdf_filename, dpi=300)
    print(f"Successfully converted {len(pages)} pages to images.")
except Exception as e:
    print(f"Error converting PDF: {e}")
    pages = [] # Ensure 'pages' is empty if conversion fails

# Initialize dictionaries to store extracted content
extracted_text_by_page = {}
extracted_diagrams_by_page = {}

# Proceed with the rest of the plan in subsequent steps

# Assuming 'pages' is a list of PIL Images from the previous step
# Assuming 'extracted_text_by_page' and 'extracted_diagrams_by_page' dictionaries are initialized

# --- Step 2 & 3: Iterate through Pages and Extract Text/Diagrams ---
print("Processing each page for text and diagrams...")

for page_num, page_img in enumerate(pages):
    page_num_display = page_num + 1 # Use 1-based indexing for display
    print(f"\nProcessing Page {page_num_display}...")

    # Convert PIL Image to OpenCV format (BGR) for processing
    page_img_cv = cv2.cvtColor(np.array(page_img), cv2.COLOR_RGB2BGR)
    gray = cv2.cvtColor(page_img_cv, cv2.COLOR_BGR2GRAY)

    # --- Text Extraction (from previous code) ---
    # Apply adaptive thresholding for better handling of varying lighting conditions
    thresh_text = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 11, 2)

    # Perform OCR with bounding box information
    text_data = pytesseract.image_to_data(page_img_cv, output_type=pytesseract.Output.DICT)

    # Extract text and store it
    page_text = pytesseract.image_to_string(page_img)
    extracted_text_by_page[page_num_display] = page_text
    print(f"Extracted text for Page {page_num_display}.")

    # Extract text regions with confidence scores for diagram filtering
    text_regions = []
    n_boxes = len(text_data['level'])
    for j in range(n_boxes):
        if text_data['text'][j].strip():
            (x, y, w, h) = (text_data['left'][j], text_data['top'][j], text_data['width'][j], text_data['height'][j])
            conf = text_data['conf'][j]
            # Filter out very low confidence text as potential noise, but keep regions that might be figure labels
            if int(conf) > 30 or re.search(r"Fig\.?\s*\d+(\.\d+)*|Figure\s*\d+(\.\d+)*", text_data['text'][j].strip(), re.IGNORECASE):
                 text_regions.append({'box': (x, y, w, h), 'text': text_data['text'][j], 'conf': conf})


    # --- Diagram Extraction (adapted from previous code) ---
    thresh_diagrams = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 11, 2)

    # Use a copy of the thresholded image for contour detection
    thresh_contours = thresh_diagrams.copy()
    contours, _ = cv2.findContours(thresh_contours, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    height, width = page_img_cv.shape[:2]
    image_area = height * width

    potential_diagram_bboxes = []

    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        area = cv2.contourArea(cnt)
        bbox_area = w * h
        density = area / bbox_area if bbox_area > 0 else 0

        # Define criteria for potential diagram components (tuned for more accuracy)
        min_area = image_area * 0.001  # Lowered minimum area to catch smaller components
        max_area = image_area * 0.99  # High maximum area
        min_aspect_ratio = 0.05 # Broader aspect ratio range
        max_aspect_ratio = 20.0 # Broader aspect ratio range
        min_density = 0.05 # Lowered minimum density


        # Filter contours based on size, aspect ratio, and density
        if (area > min_area and area < max_area and
                w > 5 and h > 5 and # Also filter out very small bounding boxes
                min_aspect_ratio < (w/h if h > 0 else 0) < max_aspect_ratio and
                density > min_density):

             # Check if this contour's bounding box significantly overlaps with any text region
             overlap_with_text = False
             for text_region in text_regions:
                 tx, ty, tw, th = text_region['box']
                 # Calculate intersection area
                 ix1 = max(x, tx)
                 iy1 = max(y, ty)
                 ix2 = min(x + w, tx + tw)
                 iy2 = min(y + h, ty + th)

                 intersection_area = max(0, ix2 - ix1) * max(0, iy2 - iy1)
                 contour_bbox_area = w * h

                 # Define overlap threshold (e.g., if more than 60% of the contour bounding box overlaps with text)
                 # Increased overlap threshold to be more lenient with text near diagrams
                 overlap_threshold = 0.6
                 if contour_bbox_area > 0 and intersection_area / contour_bbox_area > overlap_threshold:
                     overlap_with_text = True
                     break # Found significant overlap with text, this is likely text

             # If no significant overlap with text, consider it a potential diagram component
             if not overlap_with_text:
                 potential_diagram_bboxes.append((x, y, w, h))

    print(f"Identified {len(potential_diagram_bboxes)} potential diagram components on Page {page_num_display}.")


    # --- Group nearby potential diagram components ---
    grouped_diagram_bboxes = []
    if potential_diagram_bboxes:
        # Sort bounding boxes by their top-left corner
        potential_diagram_bboxes.sort(key=lambda b: (b[1], b[0]))

        current_group = []
        for bbox in potential_diagram_bboxes:
            if not current_group:
                current_group.append(bbox)
            else:
                # Check if the current bounding box is close to the last bounding box in the current group
                # Use the bounding box that encompasses the entire current group for proximity check
                group_x1 = min([b[0] for b in current_group])
                group_y1 = min([b[1] for b in current_group])
                group_x2 = max([b[0] + b[2] for b in current_group])
                group_y2 = max([b[1] + b[3] for b in current_group])
                last_group_bbox = (group_x1, group_y1, group_x2 - group_x1, group_y2 - group_y1)


                last_x, last_y, last_w, last_h = last_group_bbox
                x, y, w, h = bbox

                # Define distance thresholds for grouping (adjusted for multi-page processing)
                # These thresholds might need further tuning
                horizontal_distance_threshold = max(last_w, w) * 0.4 # 40% of the larger width
                vertical_distance_threshold = max(last_h, h) * 0.6  # 60% of the larger height


                # Check for proximity
                is_close_horizontally = abs((x + w/2) - (last_x + last_w/2)) < (last_w/2 + w/2 + horizontal_distance_threshold)
                is_close_vertically = abs(y - last_y) < vertical_distance_threshold or \
                                      abs(y + h - (last_y + last_h)) < vertical_distance_threshold or \
                                      (y > last_y and y < last_y + last_h) or \
                                      (last_y > y and last_y < y + h)


                if is_close_horizontally and is_close_vertically:
                     current_group.append(bbox)
                else:
                    # If not close, finalize the current group and start a new one
                    grouped_diagram_bboxes.append(current_group)
                    current_group = [bbox]

        # Add the last group
        if current_group:
            grouped_diagram_bboxes.append(current_group)

    print(f"Grouped into {len(grouped_diagram_bboxes)} potential diagram regions on Page {page_num_display}.")

    # --- Extract and Save Grouped Diagrams ---
    page_diagram_paths = []
    for group_idx, group in enumerate(grouped_diagram_bboxes):
        if not group:
            continue

        # Calculate the bounding box for the entire group
        all_x = [b[0] for b in group]
        all_y = [b[1] for b in group]
        all_w = [b[2] for b in group]
        all_h = [b[3] for b in group]

        min_x = min(all_x)
        min_y = min(all_y)
        max_x = max([x + w for x, w in zip(all_x, all_w)])
        max_y = max([y + h for y, h in zip(all_y, all_h)])

        group_bbox = (min_x, min_y, max_x - min_x, max_y - min_y)

        # Add a small padding to the bounding box
        padding = 15 # Increased padding
        padded_x = max(0, group_bbox[0] - padding)
        padded_y = max(0, group_bbox[1] - padding)
        padded_w = min(page_img_cv.shape[1] - padded_x, group_bbox[2] + 2 * padding)
        padded_h = min(page_img_cv.shape[0] - padded_y, group_bbox[3] + 2 * padding)


        # Extract the diagram image based on the grouped bounding box
        extracted_diagram_img = page_img_cv[padded_y : padded_y + padded_h, padded_x : padded_x + padded_w]

        # Save the extracted diagram
        # Ensure the output directory exists (already done in the previous cell, but good practice)
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

        output_path = os.path.join(output_dir, f'page_{page_num_display}_diagram_{group_idx + 1}.png')
        cv2.imwrite(output_path, extracted_diagram_img)
        page_diagram_paths.append(output_path)
        print(f"Saved diagram group {group_idx + 1} for Page {page_num_display} to '{output_path}'")

    # Store the paths to the extracted diagrams for this page
    extracted_diagrams_by_page[page_num_display] = page_diagram_paths

print("\nFinished processing all pages.")

# Now, extracted_text_by_page and extracted_diagrams_by_page dictionaries contain the results
# extracted_text_by_page: {page_num: "text content", ...}
# extracted_diagrams_by_page: {page_num: ["path/to/diagram1.png", "path/to/diagram2.png", ...], ...}

from IPython.display import display, Image

def retrieve_page_content(page_number, text_dict, diagrams_dict):
    """
    Retrieves and displays the text and diagrams for a given page number.

    Args:
        page_number (int): The 1-based page number to retrieve.
        text_dict (dict): Dictionary where keys are page numbers and values are extracted text.
        diagrams_dict (dict): Dictionary where keys are page numbers and values are lists of diagram image paths.
    """
    print(f"--- Content for Page {page_number} ---")

    # Retrieve and display text
    if page_number in text_dict:
        print("\nExtracted Text:")
        print(text_dict[page_number])
    else:
        print("\nNo text found for this page.")

    # Retrieve and display diagrams
    if page_number in diagrams_dict and diagrams_dict[page_number]:
        print("\nExtracted Diagrams:")
        for diagram_path in diagrams_dict[page_number]:
            try:
                display(Image(filename=diagram_path))
                print(f"Displayed: {diagram_path}")
            except FileNotFoundError:
                print(f"Error: Diagram file not found at {diagram_path}")
    else:
        print("\nNo diagrams found for this page.")

retrieve_page_content(4,extracted_text_by_page, extracted_diagrams_by_page)

def retrieve_content_by_topic(topic, text_dict, diagrams_dict):
    """
    Retrieves and displays the text and diagrams for pages containing a given topic.

    Args:
        topic (str): The topic to search for.
        text_dict (dict): Dictionary where keys are page numbers and values are extracted text.
        diagrams_dict (dict): Dictionary where keys are page numbers and values are lists of diagram image paths.
    """
    found_pages = []
    for page_num, text_content in text_dict.items():
        if topic.lower() in text_content.lower():
            found_pages.append(page_num)

    if not found_pages:
        print(f"No content found for topic: '{topic}'")
        return

    print(f"--- Content for topic: '{topic}' ---")
    for page_num in sorted(found_pages):
        print(f"\n--- Page {page_num} ---")

        # Display text
        print("Extracted Text:")
        print(text_dict[page_num])

        # Display diagrams
        if page_num in diagrams_dict and diagrams_dict[page_num]:
            print("\nExtracted Diagrams:")
            for diagram_path in diagrams_dict[page_num]:
                try:
                    display(Image(filename=diagram_path))
                    print(f"Displayed: {diagram_path}")
                except FileNotFoundError:
                    print(f"Error: Diagram file not found at {diagram_path}")
        else:
            print("No diagrams found for this page.")

retrieve_content_by_topic('pros of Cloud Computing ', extracted_text_by_page, extracted_diagrams_by_page)

import os
!pip install -U langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

# create a list of documents, one for each page
documents = []
for page_num in sorted(extracted_text_by_page.keys()):
    documents.append({"page_content": extracted_text_by_page[page_num], "metadata": {"page": page_num}})

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=200,
    length_function=len,
    is_separator_regex=False,
)

chunks = []
for doc in documents:
    split_pages = text_splitter.create_documents([doc["page_content"]], metadatas=[doc["metadata"]])
    chunks.extend(split_pages)

print(f"Number of original pages: {len(extracted_text_by_page)}")
print(f"Number of chunks created: {len(chunks)}")

if chunks:
    print("\n--- Sample Chunk : ---")
    print(chunks[16].page_content[:600])
    print("\n--- Chunk Metadata: ---")
    print(chunks[0].metadata)
else:    print("No chunks were created.")

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

print("Generating embeddings for the text chunks...")

# Extract the page_content from each chunk
chunk_texts = [chunk.page_content for chunk in chunks]

# Generate embeddings
embeddings = model.encode(chunk_texts, show_progress_bar=True)

print(f"Generated {len(embeddings)} embeddings.")
print(f"Shape of one embedding: {embeddings[0].shape}")

# Store embeddings and their metadata for the next step
embedded_chunks = []
for i, chunk in enumerate(chunks):
    embedded_chunks.append({
        "content": chunk.page_content,
        "embedding": embeddings[i],
        "metadata": chunk.metadata
    })

import os

# Aggressive uninstall of potentially conflicting packages
# Include opentelemetry-semantic-conventions as it was mentioned in the previous error messages
!pip uninstall -y chromadb opentelemetry-api opentelemetry-sdk opentelemetry-exporter-otlp-proto-grpc opentelemetry-semantic-conventions uvloop

# Clear pip cache (important for clean reinstallations)
!pip cache purge

# Explicitly install uvloop before chromadb, as it's a common dependency for chromadb.api.rust
!pip install -q uvloop

# Install a known compatible version of chromadb
# Explicitly pinning to 0.4.18 to avoid potential issues with the very latest version
!pip install -q chromadb==0.4.18

import chromadb
from chromadb.utils import embedding_functions

client = chromadb.Client()

# If you used a different model, you might need to create a custom embedding function.
embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

# Create a new collection (or get an existing one)
collection_name = "pdf_document_chunks"
try:
    collection = client.get_or_create_collection(
        name=collection_name,
        embedding_function=embedding_function
    )
    print(f"Collection '{collection_name}' ready.")
except Exception as e:
    print(f"Error getting or creating collection: {e}")

# Prepare data for ChromaDB

ids = [f"chunk_{i}" for i in range(len(embedded_chunks))]
embeddings_to_store = [item["embedding"].tolist() for item in embedded_chunks]
metadatas = [item["metadata"] for item in embedded_chunks]
documents_to_store = [item["content"] for item in embedded_chunks]

# Add the chunks to the ChromaDB collection
if len(ids) == len(embeddings_to_store) == len(metadatas) == len(documents_to_store):
    try:
        collection.add(
            ids=ids,
            embeddings=embeddings_to_store,
            metadatas=metadatas,
            documents=documents_to_store
        )
        print(f"Successfully added {len(ids)} chunks to the collection '{collection_name}'.")
        print(f"Total items in collection: {collection.count()}")
    except Exception as e:
        print(f"Error adding documents to collection: {e}")
        print(f"Lengths: ids={len(ids)}, embeddings={len(embeddings_to_store)}, metadatas={len(metadatas)}, documents={len(documents_to_store)}")
else:
    print("Error: Mismatch in lengths of data to be added to ChromaDB.")
    print(f"Lengths: ids={len(ids)}, embeddings={len(embeddings_to_store)}, metadatas={len(metadatas)}, documents={len(documents_to_store)}")

query_document("Pros of cloud computing", model, collection)

import matplotlib.pyplot as plt

# Define a sample query
user_query_for_plot = "Pros of cloud computing"

print(f"Retrieving chunks and distances for query: '{user_query_for_plot}'")

# Generate embedding for the user query
query_embedding_for_plot = model.encode([user_query_for_plot])

# Query ChromaDB for semantically similar chunks, including distances
results_for_plot = collection.query(
    query_embeddings=query_embedding_for_plot.tolist(),
    n_results=5, # Get the top 5 chunks as requested
    include=['documents', 'metadatas', 'distances']
)

# Extract distances and page numbers
if results_for_plot['documents'] and results_for_plot['documents'][0]:
    distances = results_for_plot['distances'][0]
    # Create labels with page numbers for better context
    labels = [f"Page {m.get('page', 'N/A')}" for m in results_for_plot['metadatas'][0]]

    # Sort by distance for better visualization (closest first)
    sorted_data = sorted(zip(distances, labels), key=lambda x: x[0])
    sorted_distances = [d for d, _ in sorted_data]
    sorted_labels = [l for _, l in sorted_data]

    # Plotting the distances
    plt.figure(figsize=(10, 6))
    plt.barh(sorted_labels, sorted_distances, color='lightcoral')
    plt.xlabel('Vector Distance (Lower = More Similar)')
    plt.ylabel('Document Chunk (Page Number)')
    plt.title(f'Vector Distances of Top 5 Chunks for: "{user_query_for_plot}"')
    plt.grid(axis='x', linestyle='--', alpha=0.7)
    plt.gca().invert_yaxis() # Invert y-axis to have the most similar at the top
    plt.tight_layout()
    plt.show()
else:
    print("No relevant chunks found to plot distances for.")

"""### Step 1: Download the quantized TinyLlama GGUF model

We'll use `huggingface_hub` to download a highly quantized version of TinyLlama. I'm choosing `tinyllama-1.1b-chat-v1.0.Q2_K.gguf` for its small size (`Q2_K` indicates a 2-bit quantization, which is very light on RAM) and chat capabilities, making it a good starting point for your laptop.
"""

from huggingface_hub import hf_hub_download
import os
from google.colab import drive

# Mount Google Drive for persistent storage
drive.mount('/content/drive')

# Changed model_name to use 'TheBloke' repository for easier access
model_name = "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF"
model_file = "tinyllama-1.1b-chat-v1.0.Q2_K.gguf" # This is a highly quantized version (2-bit)

# Define the path in Google Drive
drive_model_dir = "/content/drive/My Drive/colab_models"
os.makedirs(drive_model_dir, exist_ok=True)
drive_model_path = os.path.join(drive_model_dir, model_file)

# Define a local directory (for initial download if not in Drive, or if Drive is not mounted)
local_model_dir = "./models"
os.makedirs(local_model_dir, exist_ok=True)
local_model_path = os.path.join(local_model_dir, model_file)


# Check if the model already exists in Google Drive
if os.path.exists(drive_model_path):
    print(f"Model already exists in Google Drive at: {drive_model_path}")
    model_path = drive_model_path
else:
    print(f"Downloading {model_file} from {model_name} to {local_model_dir}...")
    # Download to local_model_dir first
    model_path = hf_hub_download(repo_id=model_name, filename=model_file, local_dir=local_model_dir)
    print(f"Model downloaded to: {model_path}")

    # Copy to Google Drive for persistent storage
    print(f"Copying model to Google Drive for persistence: {drive_model_path}")
    import shutil
    shutil.copy(model_path, drive_model_path)
    print("Model copied to Google Drive.")
    model_path = drive_model_path # Ensure model_path points to the Drive location

print(f"Using model from: {model_path}")

"""### Step 2: Install `llama-cpp-python`

`llama-cpp-python` is a Python binding for `llama.cpp`, which allows us to load and run GGUF models efficiently on the CPU. We will install it with `flash-attn` support if a GPU is available (though for your CPU, it mostly means robust CPU-based optimizations).
"""

!pip install llama-cpp-python

"""### Step 3: Load the TinyLlama Model and Interact"""

from llama_cpp import Llama

# Re-using the model_path from the download step
# If you restarted your session, you might need to re-run the download cell
# model_path = "./models/tinyllama-1.1b-chat-v1.0.Q2_K.gguf" # Uncomment and run if model_path is not defined

print(f"Loading model from: {model_path}")

# Initialize the Llama model
# n_ctx sets the maximum context window size (tokens the model can consider)
# n_gpu_layers=0 ensures it runs on CPU. Adjust if you have a GPU and llama-cpp-python was built with GPU support.
llm = Llama(model_path=model_path, n_ctx=2048, n_gpu_layers=0, verbose=False)

print("Model loaded successfully!")

# Example interaction
user_input = "Hello, what can you do?"
print(f"\nUser: {user_input}")

# Generate a response
output = llm.create_chat_completion(
    messages=[
        {"role": "system", "content": "You are a helpful AI assistant."},
        {"role": "user", "content": user_input}
    ],
    max_tokens=100, # Limit the response length for quicker generation
    temperature=0.7 # Adjust for creativity (higher = more creative)
)

# Extract and print the model's response
model_response = output["choices"][0]["message"]["content"]
print(f"TinyLlama: {model_response}")

"""## Define RAG Query Function

### Subtask:
Create a Python function that orchestrates the Retrieval Augmented Generation (RAG) process. This function will accept a user query, retrieve relevant document chunks, construct a prompt for the LLM, and generate a response.

**Reasoning**:
Now that the `rag_query` function is defined, I will add the logic to retrieve relevant document chunks using the `query_document` function within `rag_query` to fulfill the next part of the subtask.
"""

def rag_query(user_query: str, model, llm, collection, n_results: int = 5):
    """
    Orchestrates the Retrieval Augmented Generation (RAG) process.
    Accepts a user query, retrieves relevant document chunks, constructs a prompt for the LLM,
    and generates a response.

    Args:
        user_query (str): The question or query provided by the user.
        model: The loaded SentenceTransformer model used for embedding queries.
        llm: The loaded TinyLlama LLM instance.
        collection: The ChromaDB collection containing the document chunks.
        n_results (int, optional): The number of relevant chunks to retrieve from ChromaDB.
    """
    print(f"Processing RAG query for: '{user_query}'")

    # 1. Retrieve relevant document chunks
    # The query_document function already handles embedding the query and searching the collection
    # We will modify it slightly to return the results instead of printing them directly.

    # Generate embedding for the user query
    query_embedding = model.encode([user_query])

    # Query ChromaDB for semantically similar chunks
    results = collection.query(
        query_embeddings=query_embedding.tolist(), # Convert numpy array to list
        n_results=n_results,
        include=['documents', 'metadatas', 'distances']
    )

    # Extract relevant documents and their metadata
    retrieved_docs = []
    if results['documents'] and results['documents'][0]:
        for i in range(len(results['documents'][0])):
            doc_content = results['documents'][0][i]
            doc_metadata = results['metadatas'][0][i]
            page_num = doc_metadata.get('page', 'N/A')
            retrieved_docs.append({"content": doc_content, "page": page_num})

    print(f"Retrieved {len(retrieved_docs)} relevant document chunks.")

    # 2. Construct a prompt with the retrieved context for the TinyLlama LLM
    context_text = "\n\n".join([doc["content"] for doc in retrieved_docs])

    system_message = "You are a helpful AI assistant. Use the following context to answer the user's question."
    if not retrieved_docs:
        system_message += " If the answer is not in the context, state that you don't have enough information."
    else:
        system_message += " If the answer is not in the context, politely state that the provided information does not directly answer the question."


    messages = [
        {"role": "system", "content": system_message},
        {"role": "user", "content": f"Context: {context_text}\n\nQuestion: {user_query}"}
    ]

    # 3. Generate a response from the LLM
    print("Generating response from TinyLlama LLM...")
    output = llm.create_chat_completion(
        messages=messages,
        max_tokens=500, # Increased max_tokens for potentially longer answers
        temperature=0.7 # Adjust for creativity
    )

    llm_response = output["choices"][0]["message"]["content"]

    # 4. Display the formatted answer
    print(f"\n--- LLM Response for '{user_query}' ---")
    print(llm_response)

    print("\n--- Source Pages ---")
    for doc in retrieved_docs:
        print(f"- Page {doc['page']}")

rag_query("What are the pros of cloud computing?", model, llm, collection)

rag_query("What is Public Cloud?", model, llm, collection)



"""## Summary:

### Q&A
The LLM has been successfully integrated into the RAG pipeline through the `rag_query` function. This function orchestrates the retrieval of relevant document chunks, constructs a context-aware prompt for the TinyLlama LLM, and generates a coherent response.

Users can now interact with the system by calling the `rag_query` function with their specific question (e.g., `rag_query("Your question here?", model, llm, collection)`). The system will then search the provided document collection for relevant information, use that information to inform the LLM's answer, and present the response along with the page numbers from which the information was sourced.

### Data Analysis Key Findings
*   The `rag_query` function was successfully defined to orchestrate the RAG process, taking a user query, a SentenceTransformer model for embeddings, the TinyLlama LLM, a ChromaDB collection, and an optional `n_results` parameter (defaulting to 5).
*   The function retrieves relevant document chunks by embedding the user query and querying the ChromaDB collection. For the test query "What are the pros of cloud computing?", 5 relevant document chunks were successfully retrieved.
*   A context-aware prompt is constructed for the LLM, including a system message guiding it to use the provided context and gracefully handle cases where information is not found.
*   The TinyLlama LLM generates responses based on the retrieved context, and for the test query, it provided a detailed answer including pros and cons of cloud computing.
*   The system displays the LLM's response, followed by a list of source page numbers (e.g., Page 5, Page 4, Page 7), ensuring traceability and credibility of the generated information.

### Insights or Next Steps
*   The established RAG pipeline enables users to efficiently extract specific information from a document collection using natural language queries, providing answers grounded in the document's content with verifiable sources.
*   Further enhancements could include implementing a user-friendly interface (e.g., a web application) to simplify interaction for end-users, alongside exploring more advanced prompt engineering techniques or different LLM parameters to optimize response quality and relevance.

## Define MCQ Generation Function

### Subtask:
Create a Python function, `generate_mcq_quiz`, that accepts a quiz `topic`, an embedding `model`, an `llm` instance, a ChromaDB `collection`, and parameters for the number of questions and options. This function will orchestrate the entire MCQ generation process.
"""

import re # Import re for regular expressions

def generate_mcq_quiz(quiz_topic: str, model, llm, collection, num_questions: int = 3, num_options: int = 4):
    """
    Generates a multiple-choice quiz based on a given topic, retrieving relevant context,
    and using an LLM to create questions and options.

    Args:
        quiz_topic (str): The topic for which the quiz will be generated.
        model: The SentenceTransformer embedding model instance.
        llm: The TinyLlama LLM instance.
        collection: The ChromaDB collection containing document chunks.
        num_questions (int): The desired number of multiple-choice questions.
        num_options (int): The desired number of options for each question.
    """
    print(f"Generating MCQ quiz for topic: '{quiz_topic}' with {num_questions} questions and {num_options} options.")

    # 1. Generate embedding for the quiz_topic
    topic_embedding = model.encode([quiz_topic])

    # 2. Query ChromaDB for relevant document chunks
    # Reduced n_context_chunks to fit within the TinyLlama's context window
    n_context_chunks = 2 # Adjusted from 10 to 2 to avoid exceeding context window
    results = collection.query(
        query_embeddings=topic_embedding.tolist(),
        n_results=n_context_chunks,
        include=['documents', 'metadatas']
    )

    # 3. Extract the content from these retrieved document chunks
    retrieved_docs_content = []
    if results['documents'] and results['documents'][0]:
        for doc_content in results['documents'][0]:
            retrieved_docs_content.append(doc_content)

    # 4. Concatenate the extracted document content into a single string to form the context_text
    context_text = "\n\n".join(retrieved_docs_content)
    if not context_text:
        print("Warning: No relevant context found for the quiz topic. The quiz might be generic or inaccurate.")
        # Fallback if no context found, create a generic message
        context_text = "No specific context available. Generate general questions about the topic."

    # 5. Construct the LLM prompt for quiz generation
    system_prompt = (
        "You are a helpful AI assistant tasked with creating multiple-choice questions. "
        "You will be provided with a context to generate questions from. "
        "Your response MUST be a JSON array of questions, with no conversational text or preamble. "
        "Each question object in the array MUST have the following structure: "
        "{\"question\": \"Your question text\", \"options\": [\"Option A\", \"Option B\", \"Option C\", ...], \"answer\": \"Correct option text\"}."
        "Ensure the 'answer' exactly matches one of the 'options'."
    )

    user_prompt = (
        f"Based on the following context, generate {num_questions} multiple-choice questions. "
        f"Each question should have {num_options} options, and explicitly state the correct answer within the JSON structure. "
        "The questions should be directly derived from the provided context. "
        "Return ONLY the JSON array of questions, with NO additional text, conversational preamble, or explanations whatsoever. " # Emphasize pure JSON output
        "Place the JSON output strictly within a single set of triple backticks and 'json' tag (```json ... ```)." # New instruction for markdown code block
        "\n\nContext:\n" + context_text + "\n\n```json\n" # Prepend with ```json
    )

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]

    # 6. Generate the quiz from the LLM
    print("Generating quiz questions using TinyLlama LLM...")
    try:
        llm_output = llm.create_chat_completion(
            messages=messages,
            max_tokens=1024, # Reduced max_tokens to prevent exceeding context window
            temperature=0.7 # Balance creativity and factual accuracy
        )
        quiz_json_string = llm_output["choices"][0]["message"]["content"]

        # Extract JSON string from markdown code block using regex to find the first block
        match = re.search(r'```json\s*(.*?)\s*```', quiz_json_string, re.DOTALL)
        if match:
            quiz_json_string = match.group(1).strip()
        else:
            # If no markdown block is found, try to parse the whole string as JSON as a fallback
            print("Warning: Could not find JSON block in LLM output. Attempting to parse raw output.")
            print(f"Raw LLM output: {quiz_json_string[:500]}...") # Print a snippet of the raw output

        # Parse the JSON string into a Python list of dictionaries
        import json
        mcq_quiz = json.loads(quiz_json_string)

        # Ensure mcq_quiz is always a list for consistent iteration
        if isinstance(mcq_quiz, dict):
            mcq_quiz = [mcq_quiz] # Fallback if LLM occasionally returns single object instead of array

        print("Quiz generated successfully!")

        # 7. Display the generated quiz questions in a formatted way, including answers
        print("\n--- Generated Quiz ---")
        if mcq_quiz:
            for i, question_obj in enumerate(mcq_quiz):
                print(f"\nQuestion {i + 1}: {question_obj['question']}")
                # Check for 'options' key before iterating
                if 'options' in question_obj and isinstance(question_obj['options'], list):
                    for j, option in enumerate(question_obj['options']):
                        print(f"  {chr(65 + j)}. {option}")
                else:
                    print("  (Options not found or malformed)")

                # Check for 'answer' key before displaying
                if 'answer' in question_obj:
                    print(f"  Correct Answer: {question_obj['answer']}") # Display the answer
                else:
                    print("  (Correct answer not found)")
        else:
            print("No questions were generated in the quiz.")

        return mcq_quiz

    except json.JSONDecodeError as e:
        print(f"Error decoding JSON from LLM output: {e}")
        print(f"Offending JSON string (first 500 chars):\n{quiz_json_string[:500]}...")
        print(f"LLM Raw Output (if available):\n{llm_output['choices'][0]['message']['content'] if 'llm_output' in locals() else 'N/A'}")
        return []
    except Exception as e:
        print(f"Error generating quiz or parsing JSON: {e}")
        print(f"LLM Raw Output (if available):\n{llm_output['choices'][0]['message']['content'] if 'llm_output' in locals() else 'N/A'}")
        return []

mcq_quiz_result = generate_mcq_quiz("Cloud Computing Basics", model, llm, collection, num_questions=3, num_options=4)

mcq_quiz_result = generate_mcq_quiz("Cloud Deployment Models", model, llm, collection, num_questions=3, num_options=4)

"""# UI try

# Task
Next, I will install `cloudflared` to expose the Streamlit application to the internet.
"""

print("Downloading cloudflared executable...")
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64

print("Making cloudflared executable...")
!chmod +x cloudflared-linux-amd64

print("Moving cloudflared to /usr/local/bin...")
!mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

print("cloudflared installed successfully! Test with: !cloudflared --version")
!cloudflared --version

"""## Run Streamlit App with Cloudflared

### Subtask:
Execute the Streamlit application using the `app.py` file. Instead of `localtunnel`, create a public tunnel using `cloudflared` to make the Streamlit UI accessible. This will provide a stable, password-free public URL.

"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import os
# import sys
# import json
# import re
# import tempfile
# import shutil
# from google.colab import drive
# from huggingface_hub import hf_hub_download
# 
# # Add the current directory to sys.path to import local modules
# sys.path.append('.')
# 
# from llama_cpp import Llama
# from sentence_transformers import SentenceTransformer
# import chromadb
# from chromadb.utils import embedding_functions
# 
# # PDF processing and OCR related imports (ensure these are available)
# from pdf2image import convert_from_path
# from PIL import Image
# import pytesseract
# import cv2
# import numpy as np
# 
# st.set_page_config(layout="wide", page_title="PDF RAG Chatbot with TinyLlama")
# 
# st.title("🧠 VECTORAG Chatbot ")
# st.markdown("Ask questions about the uploaded PDF document (Cloud Computing.pdf).")
# 
# # --- Configuration --- #
# # Re-using paths and names from previous cells
# MODEL_PATH = "/content/drive/My Drive/colab_models/tinyllama-1.1b-chat-v1.0.Q2_K.gguf"
# CHROMA_COLLECTION_NAME = "pdf_document_chunks"
# 
# # --- 0. Mount Google Drive for persistent storage ---
# # drive.mount('/content/drive', force_remount=True) # REMOVED: Must be mounted in Colab notebook, not Streamlit app
# 
# @st.cache_resource
# def load_llm():
#     """Loads the TinyLlama LLM model."""
#     st.info("Loading TinyLlama LLM... This might take a moment.")
#     try:
#         llm = Llama(model_path=MODEL_PATH, n_ctx=2048, n_gpu_layers=0, verbose=False)
#         st.success("TinyLlama LLM loaded successfully!")
#         return llm
#     except Exception as e:
#         st.error(f"Error loading LLM: {e}. Please ensure the model file is accessible at {MODEL_PATH}.")
#         st.stop()
# 
# @st.cache_resource
# def load_embedding_model():
#     """Loads the SentenceTransformer embedding model."""
#     st.info("Loading embedding model...")
#     try:
#         model = SentenceTransformer('all-MiniLM-L6-v2')
#         st.success("Embedding model loaded successfully!")
#         return model
#     except Exception as e:
#         st.error(f"Error loading embedding model: {e}")
#         st.stop()
# 
# @st.cache_resource
# def load_chroma_collection(_embedding_model): # Changed to _embedding_model
#     """Loads the ChromaDB collection."""
#     st.info("Loading ChromaDB collection...")
#     try:
#         client = chromadb.Client()
#         embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")
#         collection = client.get_or_create_collection(
#             name=CHROMA_COLLECTION_NAME,
#             embedding_function=embedding_function
#         )
#         st.success(f"ChromaDB collection '{CHROMA_COLLECTION_NAME}' loaded with {collection.count()} items.")
#         return collection
#     except Exception as e:
#         st.error(f"Error loading ChromaDB collection: {e}. Please ensure ChromaDB is initialized.")
#         st.stop()
# 
# # Load resources
# with st.spinner("Initializing models and vector database..."):
#     llm_model = load_llm()
#     embedding_model_instance = load_embedding_model()
#     chroma_collection = load_chroma_collection(embedding_model_instance) # Pass the instance
# st.success("Initialization complete!")
# 
# # Initialize session state for tracking processed file
# if 'processed_file_name' not in st.session_state:
#     st.session_state.processed_file_name = None
# if 'document_processed' not in st.session_state:
#     st.session_state.document_processed = False
# 
# 
# # --- PDF Processing Function ---
# def process_uploaded_pdf(uploaded_file, embedding_model, chromadb_collection):
#     with st.spinner("Processing PDF, please wait... This may take a few minutes."):
#         try:
#             # Create a temporary directory
#             with tempfile.TemporaryDirectory() as tmpdir:
#                 temp_pdf_path = os.path.join(tmpdir, uploaded_file.name)
#                 with open(temp_pdf_path, "wb") as f:
#                     f.write(uploaded_file.getbuffer())
# 
#                 st.info("Converting PDF to images...")
#                 pages = convert_from_path(temp_pdf_path, dpi=300)
#                 st.success(f"Successfully converted {len(pages)} pages to images.")
# 
#                 extracted_text_by_page = {}
# 
#                 progress_bar = st.progress(0)
#                 status_text = st.empty()
# 
#                 # Extract text from each page
#                 st.info("Extracting text from pages using OCR...")
#                 for page_num, page_img in enumerate(pages):
#                     page_num_display = page_num + 1
#                     status_text.text(f"Processing page {page_num_display}/{len(pages)} for text...")
#                     page_text = pytesseract.image_to_string(page_img)
#                     extracted_text_by_page[page_num_display] = page_text
#                     progress_bar.progress((page_num + 1) / len(pages))
#                 st.success("Text extraction complete.")
# 
#                 # Chunking
#                 text_splitter = RecursiveCharacterTextSplitter(
#                     chunk_size=800,
#                     chunk_overlap=200,
#                     length_function=len,
#                     is_separator_regex=False,
#                 )
# 
#                 chunks = []
#                 for page_num in sorted(extracted_text_by_page.keys()):
#                     doc_content = extracted_text_by_page[page_num]
#                     doc_metadata = {"page": page_num}
#                     split_pages = text_splitter.create_documents([doc_content], metadatas=[doc_metadata])
#                     chunks.extend(split_pages)
#                 st.success(f"Created {len(chunks)} chunks.")
# 
#                 # Generate embeddings
#                 chunk_texts = [chunk.page_content for chunk in chunks]
#                 embeddings = embedding_model.encode(chunk_texts)
# 
#                 # Prepare data for ChromaDB
#                 ids = [f"chunk_{i}" for i in range(len(chunks))]
#                 embeddings_to_store = [item.tolist() for item in embeddings]
#                 metadatas = [chunk.metadata for chunk in chunks]
#                 documents_to_store = [chunk.page_content for chunk in chunks]
# 
#                 # Clear existing collection and add new data
#                 try:
#                     chromadb_collection.delete(ids=[f"chunk_{i}" for i in range(chromadb_collection.count())]) # Clear existing if any
#                     st.info("Cleared existing ChromaDB collection.")
#                 except Exception as e:
#                     st.warning(f"Could not clear old collection (may be empty): {e}")
# 
#                 if len(ids) == len(embeddings_to_store) == len(metadatas) == len(documents_to_store):
#                     chromadb_collection.add(
#                         ids=ids,
#                         embeddings=embeddings_to_store,
#                         metadatas=metadatas,
#                         documents=documents_to_store
#                     )
#                     st.success(f"Successfully added {len(ids)} chunks to ChromaDB. Total items: {chromadb_collection.count()}")
#                     return True
#                 else:
#                     st.error("Error: Mismatch in lengths of data to be added to ChromaDB.")
#                     return False
# 
#         except Exception as e:
#             st.error(f"An error occurred during PDF processing: {e}")
#             return False
# 
# 
# 
# # --- 1. Document Upload Section ---
# st.header("1. Document Upload")
# st.write("Upload your PDF document here to begin. The content will be processed and used for RAG queries and quiz generation.")
# 
# uploaded_file = st.file_uploader("Choose a PDF file", type="pdf")
# 
# if uploaded_file is not None:
#     if st.session_state.processed_file_name != uploaded_file.name:
#         st.session_state.processed_file_name = uploaded_file.name
#         st.session_state.document_processed = False # Reset processing status for new file
# 
#         st.info(f"New file '{uploaded_file.name}' detected. Starting processing...")
#         # Add this import here, as it's needed for chunking in this scope
#         from langchain_text_splitters import RecursiveCharacterTextSplitter
#         success = process_uploaded_pdf(uploaded_file, embedding_model_instance, chroma_collection)
#         if success:
#             st.session_state.document_processed = True
#         else:
#             st.session_state.document_processed = False
#     else:
#         st.info(f"Document '{uploaded_file.name}' is already processed.")
#         st.session_state.document_processed = True
# else:
#     st.info("Please upload a PDF document to start.")
#     st.session_state.document_processed = False
# 
# 
# # --- Functions for RAG and Quiz (from previous steps, adapted for Streamlit) ---
# def rag_query_streamlit(user_query: str, embed_model, local_llm, collection, n_results: int = 5):
#     # 1. Retrieve relevant document chunks
#     query_embedding = embed_model.encode([user_query])
#     results = collection.query(
#         query_embeddings=query_embedding.tolist(),
#         n_results=n_results,
#         include=['documents', 'metadatas']
#     )
# 
#     retrieved_docs = []
#     if results['documents'] and results['documents'][0]:
#         for i in range(len(results['documents'][0])):
#             doc_content = results['documents'][0][i]
#             doc_metadata = results['metadatas'][0][i]
#             page_num = doc_metadata.get('page', 'N/A')
#             retrieved_docs.append({"content": doc_content, "page": page_num})
# 
#     context_text = "\n\n".join([doc["content"] for doc in retrieved_docs])
# 
#     system_message = "You are a helpful AI assistant. Use the following context to answer the user's question."
#     if not retrieved_docs:
#         system_message += " If the answer is not in the context, provide answer of your own getting through internet."
#     else:
#         system_message += " If the answer is not in the context, provide answer of your own getting through interne"
# 
#     messages = [
#         {"role": "system", "content": system_message},
#         {"role": "user", "content": f"Context: {context_text}\n\nQuestion: {user_query}"}
#     ]
# 
#     with st.spinner("Generating response from TinyLlama LLM..."):
#         output = local_llm.create_chat_completion(
#             messages=messages,
#             max_tokens=500,
#             temperature=0.7
#         )
#     llm_response = output["choices"][0]["message"]["content"]
#     source_pages = sorted(list(set([doc['page'] for doc in retrieved_docs]))) # Unique sorted pages
# 
#     return llm_response, source_pages
# 
# def generate_mcq_quiz_streamlit(quiz_topic: str, embed_model, local_llm, collection, num_questions: int = 3, num_options: int = 4):
#     st.subheader(f"Generating MCQ quiz for topic: '{quiz_topic}'")
# 
#     topic_embedding = embed_model.encode([quiz_topic])
# 
#     n_context_chunks = 2
#     results = collection.query(
#         query_embeddings=topic_embedding.tolist(),
#         n_results=n_context_chunks,
#         include=['documents', 'metadatas']
#     )
# 
#     retrieved_docs_content = []
#     if results['documents'] and results['documents'][0]:
#         for doc_content in results['documents'][0]:
#             retrieved_docs_content.append(doc_content)
# 
#     context_text = "\n\n".join(retrieved_docs_content)
#     if not context_text:
#         st.warning("No relevant context found for the quiz topic. The quiz might be generic or inaccurate.")
#         context_text = "No specific context available. Generate general questions about the topic."
# 
#     # Display retrieved context for debugging
#     with st.expander("View Retrieved Context for Quiz Generation"):
#         if context_text:
#             st.code(context_text)
#         else:
#             st.info("No context was retrieved for this topic.")
# 
#     system_prompt = (
#         "You are a helpful AI assistant tasked with creating multiple-choice questions. "
#         "You will be provided with a context to generate questions from. "
#         "Your response MUST be a JSON array of questions, with no conversational text or preamble. "
#         "Each question object in the array MUST have the following structure: "
#         "{\"question\": \"Your question text\", \"options\": [\"Option A\", \"Option B\", \"Option C\", ...], \"answer\": \"Correct option text\"}."
#         "Ensure the 'answer' exactly matches one of the 'options'."
#     )
# 
#     user_prompt = (
#         f"Based on the following context, generate {num_questions} multiple-choice questions. "
#         f"Each question should have {num_options} options, and explicitly state the correct answer within the JSON structure. "
#         "The questions should be directly derived from the provided context. "
#         "Return ONLY the JSON array of questions, with NO additional text, conversational preamble, or explanations whatsoever. "
#         "Place the JSON output strictly within a single set of triple backticks and 'json' tag (```json ... ```)."
#         "\n\nContext:\n" + context_text + "\n\n```json\n"
#     )
#     # Define messages here
#     messages = [
#         {"role": "system", "content": system_prompt},
#         {"role": "user", "content": user_prompt}
#     ]
# 
#     with st.spinner("Generating quiz questions using TinyLlama LLM..."):
#         try:
#             llm_output = local_llm.create_chat_completion(
#                 messages=messages,
#                 max_tokens=1024,
#                 temperature=0.7
#             )
#             quiz_json_string = llm_output["choices"][0]["message"]["content"]
# 
#             # Extract JSON string from markdown code block using a more flexible regex
#             match = re.search(r'```(?P<lang>\w*)?\s*(.*?)\s*```', quiz_json_string, re.DOTALL)
#             if match:
#                 quiz_json_string = match.group(2).strip()
#             else:
#                 st.warning("Could not find JSON code block in LLM output. Attempting to parse raw output directly.")
#                 st.code(quiz_json_string[:500] + "...") # Show raw output for debugging
# 
#             mcq_quiz = json.loads(quiz_json_string)
# 
#             if isinstance(mcq_quiz, dict):
#                 mcq_quiz = [mcq_quiz]
# 
#             st.success("Quiz generated successfully!")
# 
#             st.markdown("**--- Generated Quiz ---**")
#             if mcq_quiz:
#                 for i, question_obj in enumerate(mcq_quiz):
#                     st.markdown(f"**Question {i + 1}:** {question_obj.get('question', 'N/A')}")
#                     options = question_obj.get('options', [])
#                     for j, option_text in enumerate(options):
#                         st.write(f"  {chr(65 + j)}. {option_text}")
# 
#                     # Check for 'answer' and 'correct_answer' keys
#                     if 'answer' in question_obj:
#                         st.success(f"**Correct Answer:** {question_obj['answer']}")
#                     elif 'correct_answer' in question_obj: # Fallback for LLMs using different key
#                         st.warning("LLM used 'correct_answer' instead of 'answer' key. Displaying anyway.")
#                         st.success(f"**Correct Answer:** {question_obj['correct_answer']}")
#                     else:
#                         st.warning("  (Correct answer not found or malformed)")
#                     st.markdown("--- ")
#             else:
#                 st.info("No questions were generated in the quiz.")
# 
#             return mcq_quiz
# 
#         except json.JSONDecodeError as e:
#             st.error(f"Error decoding JSON from LLM output: {e}")
#             st.code(f"Offending JSON string (first 500 chars):\n{quiz_json_string[:500]}...")
#             st.code(f"Full LLM Raw Output (if available):\n{llm_output['choices'][0]['message']['content'] if 'llm_output' in locals() else 'N/A'}")
#             return []
#         except Exception as e:
#             st.error(f"Error generating quiz or parsing JSON: {e}")
#             st.code(f"Full LLM Raw Output (if available):\n{llm_output['choices'][0]['message']['content'] if 'llm_output' in locals() else 'N/A'}")
#             return []
# 
# 
# # --- Streamlit UI --- #
# 
# with st.sidebar:
#     st.header("Settings")
#     mode = st.radio("Choose Mode:", ("Q&A Chatbot", "MCQ Quiz Generator"))
#     n_results_chat = st.slider("Number of chunks for Chatbot", 1, 10, 5)
#     num_questions_quiz = st.slider("Number of questions for Quiz", 1, 10, 3)
#     num_options_quiz = st.slider("Number of options for Quiz", 2, 5, 4)
# 
# 
# if mode == "Q&A Chatbot":
#     st.header("Chat with your PDF")
#     user_question = st.text_input("Ask a question about the document:")
# 
#     if user_question:
#         with st.spinner("Getting answer from TinyLlama..."):
#             llm_response, source_pages = rag_query_streamlit(user_question, embedding_model_instance, llm_model, chroma_collection, n_results=n_results_chat)
#             st.subheader("Answer:")
#             st.write(llm_response)
# 
#             if source_pages:
#                 st.subheader("Source Pages:")
#                 st.info(f"Information primarily from page(s): {', '.join(map(str, source_pages))}")
#             else:
#                 st.info("No specific source pages identified in the retrieved context.")
# 
# elif mode == "MCQ Quiz Generator":
#     st.header("Generate MCQ Quiz from PDF")
#     quiz_topic_input = st.text_input("Enter a topic for the quiz (e.g., 'Cloud Deployment Models'):")
# 
#     if st.button("Generate Quiz") and quiz_topic_input:
#         quiz_questions = generate_mcq_quiz_streamlit(quiz_topic_input, embedding_model_instance, llm_model, chroma_collection, num_questions_quiz, num_options_quiz)
# 
#         if quiz_questions:
#             st.subheader("Generated Quiz:")
#             for i, q in enumerate(quiz_questions):
#                 st.markdown(f"**Question {i+1}:** {q.get('question', 'N/A')}")
#                 options = q.get('options', [])
#                 for j, option_text in enumerate(options):
#                     st.write(f"  {chr(65+j)}. {option_text}")
# 
#                 # Display correct answer
#                 if 'answer' in q:
#                     st.success(f"**Correct Answer:** {q['answer']}")
#                 elif 'correct_answer' in q: # Fallback for LLMs using different key
#                     st.warning("LLM used 'correct_answer' instead of 'answer' key. Displaying anyway.")
#                     st.success(f"**Correct Answer:** {q['correct_answer']}")
#                 else:
#                     st.warning("  (Correct answer not found)")
#                 st.markdown("--- ")
#         else:
#             st.warning("Could not generate quiz questions. Please try a different topic or adjust settings.")
#

"""**Reasoning**:
To run the Streamlit application, the `streamlit` library needs to be installed in the environment.


"""

print("Installing Streamlit...")
!pip install streamlit
print("Streamlit installed successfully!")

"""**Reasoning**:
Now that the `app.py` is created and Streamlit is installed, I need to run the Streamlit application in the background and then create a `cloudflared` tunnel to expose it. Running Streamlit in the background with `nohup` and `&` allows the `cloudflared` command to execute in the same cell.


"""

# Terminate any processes running on port 8501 to ensure a clean start
!fuser -k 8501/tcp

"""#### Rerunning Streamlit with Cloudflared

Now, let's restart the Streamlit app in the background and establish the `cloudflared` tunnel. This code is designed to be more robust.

"""

import subprocess
import time

print("Starting Streamlit app in background...")

# Command to run Streamlit
streamlit_cmd = [
    'streamlit',
    'run',
    'app.py',
    '--server.port',
    '8501',
    '--server.enableCORS',
    'false',
    '--server.enableXsrfProtection',
    'false'
]

# Start Streamlit as a detached process (using Popen without waiting)
# Redirecting stdout/stderr to files to prevent blocking the notebook output
with open('streamlit_output.log', 'w') as out_f, open('streamlit_error.log', 'w') as err_f:
    streamlit_process = subprocess.Popen(streamlit_cmd, stdout=out_f, stderr=err_f, preexec_fn=os.setsid)

print(f"Streamlit process started with PID: {streamlit_process.pid}. Output logged to streamlit_output.log and streamlit_error.log")

# Give Streamlit a moment to start up (adjust if needed)
time.sleep(10)

print("Creating Cloudflared tunnel...")

# Initiate cloudflared tunnel
# This will print the public URL, which needs to be copied by the user.
# This command is expected to run indefinitely, exposing the port.
# If you need to stop it, you'll need to interrupt the Colab cell execution.
!cloudflared tunnel --url http://localhost:8501



import matplotlib.pyplot as plt
import numpy as np
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.utils import embedding_functions

# --- Re-initialize model and collection (as requested to not use existing variables) ---

# 1. Load the SentenceTransformer model
print("Loading SentenceTransformer model...")
model = SentenceTransformer('all-MiniLM-L6-v2')
print("SentenceTransformer model loaded.")

# 2. Initialize ChromaDB client and get the collection
print("Initializing ChromaDB client and collection...")
client = chromadb.Client()
embedding_function = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")
collection_name = "pdf_document_chunks"

try:
    # Attempt to get an existing collection first
    collection = client.get_collection(name=collection_name, embedding_function=embedding_function)
    print(f"Existing collection '{collection_name}' retrieved with {collection.count()} items.")
except Exception as e:
    print(f"Error retrieving collection: {e}. Attempting to create a new one...")
    try:
        # If retrieval fails, try to create it. Note: For plotting, you need data in it.
        collection = client.get_or_create_collection(name=collection_name, embedding_function=embedding_function)
        print(f"Collection '{collection_name}' created/retrieved with {collection.count()} items.")
        if collection.count() == 0:
            print("Warning: Collection is empty. The graph may not show results. Please ensure previous data embedding steps were successful.")
    except Exception as e:
        print(f"Critical Error: Could not initialize ChromaDB collection: {e}")
        print("Please ensure chromadb and its dependencies are correctly installed and initialized in previous steps.")
        collection = None # Indicate that collection is not available


# --- Graph generation logic ---

if collection and collection.count() > 0:
    user_query_for_plot = "Pros of cloud computing"
    print(f"\nRetrieving chunks and distances for query: '{user_query_for_plot}'")

    # Generate embedding for the user query
    query_embedding_for_plot = model.encode([user_query_for_plot])

    # Query ChromaDB for semantically similar chunks, including distances
    results_for_plot = collection.query(
        query_embeddings=query_embedding_for_plot.tolist(),
        n_results=5, # Get the top 5 chunks as requested
        include=['documents', 'metadatas', 'distances']
    )

    # Extract distances and page numbers
    if results_for_plot['documents'] and results_for_plot['documents'][0]:
        distances = results_for_plot['distances'][0]
        # Create labels with page numbers for better context
        labels = [f"Page {m.get('page', 'N/A')}" for m in results_for_plot['metadatas'][0]]

        # Sort by distance for better visualization (closest first)
        sorted_data = sorted(zip(distances, labels), key=lambda x: x[0])
        sorted_distances = [d for d, _ in sorted_data]
        sorted_labels = [l for _, l in sorted_data]

        # Plotting the distances
        plt.figure(figsize=(10, 6))
        plt.barh(sorted_labels, sorted_distances, color='lightcoral')
        plt.xlabel('Vector Distance (Lower = More Similar)')
        plt.ylabel('Document Chunk (Page Number)')
        plt.title(f'Vector Distances of Top 5 Chunks for: "{user_query_for_plot}"')
        plt.grid(axis='x', linestyle='--', alpha=0.7)
        plt.gca().invert_yaxis() # Invert y-axis to have the most similar at the top
        plt.tight_layout()
        plt.show()
    else:
        print("No relevant chunks found to plot distances for the query.")
else:
    print("Cannot generate graph: ChromaDB collection is not available or is empty.")

import matplotlib.pyplot as plt
import numpy as np

# Replace these with real ChromaDB query results:
# distances = results['distances'][0]
# labels = [f"Page {m.get('page', 'N/A')}" for m in results['metadatas'][0]]
distances = [0.12, 0.25, 0.38, 0.45, 0.52]  # Example cosine distances (lower = more similar)
labels = ["Page 4", "Page 1", "Page 5", "Page 7", "Page 10"]

# Sort by distance (closest/most similar first)
sorted_data = sorted(zip(distances, labels), key=lambda x: x[0])
sorted_distances = [d for d, _ in sorted_data]
sorted_labels = [l for _, l in sorted_data]

# Create the plot with improved readability
fig, ax = plt.subplots(figsize=(12, 8))
bars = ax.barh(sorted_labels, sorted_distances, color='lightcoral', alpha=0.8)
ax.set_xlabel('Vector Distance (Lower = More Similar)', fontsize=12)
ax.set_ylabel('Document Chunk', fontsize=12)
ax.set_title('Top 5 Chunk Distances for "Pros of cloud computing"', fontsize=14, pad=20)
ax.grid(axis='x', linestyle='--', alpha=0.7)
ax.invert_yaxis()  # Most similar at top

# Add distance values on bars
for i, (bar, dist) in enumerate(zip(bars, sorted_distances)):
    ax.text(dist + 0.01, bar.get_y() + bar.get_height()/2, f'{dist:.2f}',
            ha='left', va='center', fontsize=10)

plt.tight_layout()
plt.savefig('chunk_distances.png', dpi=300, bbox_inches='tight')  # Save as PNG
plt.show()  # Or display interactively